### PR TITLE
Fix failing tracking test

### LINKED ISSUE #928: [BUG] TRACKING_TEST only works with RMM_LOGGING_LEVEL=DEBUG
**Describe the bug**
After #920 is merged, running tests from head fails:
```console
[ RUN      ] TrackingTest.LogOutstandingAllocations
/home/rou/src/rmm/tests/mr/device/tracking_mr_tests.cpp:217: Failure
Expected: (oss.str().find("Outstanding Allocations")) != (std::string::npos), actual: 18446744073709551615 vs 18446744073709551615
```

**Steps/Code to reproduce bug**
Sync to head, run cmake and ninja, invoke `./gtests/TRACKING_TEST`.

**Expected behavior**
Tests should pass with the default configuration.

**Environment details (please complete the following information):**
 - Environment location: Bare-metal
 - Method of RMM install: from source

**Additional context**
Seems like the logging level is determined at compile time, while the test is trying to modify it at runtime. The only way to get the test to pass is to run `cmake .. -DRMM_LOGGING_LEVEL=DEBUG`.

### PR DESCRIPTION
**Pull request by harrism**
Fixes #928.

#920 introduced a new test for the `tracking_resource_adaptor::log_outstanding_allocations`, but that function only logs when `SPDLOG_ACTIVE_LEVEL <= SPDLOG_LEVEL_DEBUG`, so the test needs to be gated on that condition as well.

### CODE REVIEW

File: tests/mr/device/tracking_mr_tests.cpp [hunk 1]
```diff
@@ -213,12 +213,15 @@ TEST(TrackingTest, LogOutstandingAllocations)
...
-  mr.log_outstanding_allocations();
+  EXPECT_NO_THROW(mr.log_outstanding_allocations());
+
+#if SPDLOG_ACTIVE_LEVEL <= SPDLOG_LEVEL_DEBUG
   EXPECT_NE(oss.str().find("Outstanding Allocations"), std::string::npos);
 
   for (auto& allocation : allocations) {
     mr.deallocate(allocation, ten_MiB);
   }
+#endif
```
Comment (rongou) [inline tests/mr/device/tracking_mr_tests.cpp:224]: Shouldn't this be after line 219?

Comment (harrism) [reply tests/mr/device/tracking_mr_tests.cpp:224]: Yeah, not sure what happened here.

**Review by rongou — APPROVED** [review]

**Review by vyasr — APPROVED** [review]

**Review by bdice — APPROVED** [review]

**Comment by harrism** [comment]
@gpucibot merge
