### PR TITLE
Avoid accessing statistics_resource_adaptor stack top if it is empty

### LINKED ISSUE #1587: [BUG] statistics_resource_adaptor UB when empty stack is accessed
**Describe the bug**
`statistics_resource_adaptor` now contains a stack, and there are several calls to `std::stack::top()` without checking whether the stack is empty. Just like accessing `back()` on an empty `vector`, calling `top()` or `pop()` on an empty stack results in undefined behavior (UB). 

I found this because in a debug build of RMM I see segmentation faults in `ADAPTOR_TEST` when testing the `statistics_resource_adaptor`

Example location: 
https://github.com/rapidsai/rmm/blob/1ab4920e50a07a97ec717db514ad9a3dccc9939a/include/rmm/mr/device/statistics_resource_adaptor.hpp#L189

**Steps/Code to reproduce bug**
Build debug, run tests, get segfault.

**Expected behavior**

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of RMM install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
 - Please run and attach the output of the `rmm/print_env.sh` script to gather relevant environment details

**Additional context**

### PR DESCRIPTION
**Pull request by harrism**
## Description
Fixes #1587 

Note: the only time UB could occur was in the constructor, because the ctor pushes a pair onto the stack and `pop_counters()` does not allow the last pair to be popped. Therefore, we only need to check for empty in `push_counters()`.

## Checklist
- [X] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rmm/blob/HEAD/CONTRIBUTING.md).
- [X] New or existing tests cover these changes.
- [X] The documentation is up to date with these changes.

### CODE REVIEW

**Review by madsbk — APPROVED** [review]
Good catch

File: include/rmm/mr/device/statistics_resource_adaptor.hpp [hunk 1]
```diff
@@ -186,8 +186,8 @@ class statistics_resource_adaptor final : public device_memory_resource {
   std::pair<counter, counter> push_counters()
   {
     write_lock_t lock(mtx_);
-    auto ret = counter_stack_.top();
-    counter_stack_.push(std::make_pair(counter{}, counter{}));
+    auto ret = counter_stack_.empty() ? std::make_pair(counter{}, counter{}) : counter_stack_.top();
+    counter_stack_.push({counter{}, counter{}});
```
Comment (wence-) [inline include/rmm/mr/device/statistics_resource_adaptor.hpp:190]: *question*: While this fixes the issue. It does (internally) invalidate the docstring (in the ctor the return value from counter_stack_ is the newly pushed set of counters, though it doesn't matter because it's ignored).

There's also some action-at-distance in that it's not fully obvious that the reason for the `push_counters` in the ctor is that one needs to maintain the invariant that the counter stack always has at least one entry.

Can we instead just initialize the counter stack appropriately at construction time, then the necessary invariant for the stack is always true:
```diff
diff --git a/include/rmm/mr/device/statistics_resource_adaptor.hpp b/include/rmm/mr/device/statistics_resource_adaptor.hpp
index c8906afd..40a247ff 100644
--- a/include/rmm/mr/device/statistics_resource_adaptor.hpp
+++ b/include/rmm/mr/device/statistics_resource_adaptor.hpp
@@ -122,8 +122,6 @@ class statistics_resource_adaptor final : public device_memory_resource {
   statistics_resource_adaptor(Upstream* upstream) : upstream_{upstream}
   {
     RMM_EXPECTS(nullptr != upstream, "Unexpected null upstream resource pointer.");
-    // Initially, we push a single counter pair on the stack
-    push_counters();
   }
 
   statistics_resource_adaptor()                                              = delete;
@@ -196,6 +194,7 @@ class statistics_resource_adaptor final : public device_memory_resource {
    *
    * @return top pair of counters <bytes, allocations> from the stack _before_
    * the pop
+   * @throws std::out_of_range if the counter stack has fewer than two entries.
    */
   std::pair<counter, counter> pop_counters()
   {
@@ -275,7 +274,8 @@ class statistics_resource_adaptor final : public device_memory_resource {
   }
 
   // Stack of counter pairs <bytes, allocations>
-  std::stack<std::pair<counter, counter>> counter_stack_;
+  // Invariant: the stack always contains at least one entry
+  std::stack<std::pair<counter, counter>> counter_stack_{{std::make_pair(counter{}, counter{})}};
   std::shared_mutex mutable mtx_;  // mutex for thread safe access to allocations_
   Upstream* upstream_;             // the upstream resource used for satisfying allocation requests
 };
```
WDYT?

**Review by wence- — APPROVED** [review]
non-blocking suggestion.

File: include/rmm/mr/device/statistics_resource_adaptor.hpp (hunk 1 above)
Comment (madsbk) [reply include/rmm/mr/device/statistics_resource_adaptor.hpp:190]: LGTM

Comment (harrism) [reply include/rmm/mr/device/statistics_resource_adaptor.hpp:190]: Yeah, I think this is a good idea. I started something similar but got lazy. 

I find it a little bit incongruous to throw std::out_of_range here when std::stack (and the underlying container it is built on) do not throw when you `pop()`/`pop_back` an empty container: it is just UB.

More importantly, I need to ask: is `pop_counters()` likely to be called from a destructor or memory deallocation? If so, it must be `noexcept`. It *will* be called at the point where destruction happens -- when leaving scope. If it is implemented using RAII, then it is called in a dtor, and so must be `noexcept`.  Thoughts?

Comment (wence-) [reply include/rmm/mr/device/statistics_resource_adaptor.hpp]: > More importantly, I need to ask: is pop_counters() likely to be called from a destructor or memory deallocation? If so, it must be noexcept. It will be called at the point where destruction happens -- when leaving scope. If it is implemented using RAII, then it is called in a dtor, and so must be noexcept. Thoughts?

`pop_counters` is not called by destructors in the current implementation, and the usage right now is of the form:

```
auto some_func(...)
{
   mr.push_counters();
   make_calls_that_allocate/deallocate();
   stats = mr.pop_counters();
   // record stats somewhere
}
```

Which I think is safe. If one wanted to wrap that push/pop/record idiom in an RAII object, then yes, we would need to change `pop_counters()` to `noexcept` and (instead of `throw`ing) `debug_assert` if the stack invariant is not maintained due to mismatched push/pop pairs.

**Review by rongou — APPROVED** [review]

File: include/rmm/mr/device/statistics_resource_adaptor.hpp (hunk 1 above)
Comment (harrism) [reply include/rmm/mr/device/statistics_resource_adaptor.hpp]: Seems to me this should be a debug assert and not a throw. 
 * This would allow us to add RAII functionality, and make it easier to use in an NVTX RAII object.
 * The invariant is documented and maintained by all correct usage of the class.
 * The underlying C++ containers don't throw, they document it as UB

Comment (harrism) [reply include/rmm/mr/device/statistics_resource_adaptor.hpp]: Argh, `std::shared_mutex::lock()` can throw `std::system_error`. Rare, but making these functions `noexcept` would be wrong...
