### PR TITLE
Inline functions that return static references must have default visibility

### LINKED ISSUE #1651: [BUG] Not all global static references are `__attribute__((visibility(default)))`
**Describe the bug**

In #826, it was noted that the `std::map` in `per_device_resource.hpp` is a global static reference returned from an inline function. This causes issues with the RMM-default `visibility(hidden)` attribute of functions in the RMM headers, since although when compiling _within a single library_, the linker will uniquify the references to the function, when RMM is included in two separate libraries, this does not occur.

As a consequence, with `visibility(hidden)`, the static reference will be unique per library, but differ across libraries.

#833 fixed this for the particular case of `rmm::mr::detail::get_map`, by making that function `RMM_EXPORT`.

However, there are other static references returned from inline functions in that file that were not exported. These should also be `RMM_EXPORT`.

In particular `rmm::mr::detail::map_lock` returns a static reference to a mutex that protects accesses to the per-device-resource map. However, since it is visibility(hidden), we actually don't have a single map lock, and so we are actually _not_ protecting concurrent access to the per-device-resource map from _different_ libraries.

An example, printing the address of the map lock:
```diff --git a/include/rmm/mr/device/per_device_resource.hpp b/include/rmm/mr/device/per_device_resource.hpp
index a56a784a..d5afafe4 100644
--- a/include/rmm/mr/device/per_device_resource.hpp
+++ b/include/rmm/mr/device/per_device_resource.hpp
@@ -108,6 +108,7 @@ inline device_memory_resource* initial_resource()
 inline std::mutex& map_lock()
 {
   static std::mutex map_lock;
+  std::cout << "Map lock " << &map_lock << std::endl; 
   return map_lock;
 }
```

We see, when cudf is compiled and used from cudf python (the python bindings build a separate library that includes RMM):

```python
import cudf
s = cudf.Series([1])
```
prints
```
Map lock 0x7355ec744e20
Map lock 0x7355bc40c400
```

### PR DESCRIPTION
**Pull request by wence-**
## Description

In #833, we gave `rmm::mr::detail::get_map` default visibility. However, there are a number of other functions that return static references that should also have this visibility so that the static reference is unique across multiple DSOs.

- Closes #1651

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rmm/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by wence-** [comment]
Technically this is "breaking", since it changes symbol visibility. But I think it's ok to be non-breaking.

**Comment by wence-** [comment]
doc build fails because breathe doesn't know how to deal with the definition `RMM_EXPORT inline spdlog::logger& logger`. I don't know enough doxygen to figure out how to elide the `RMM_EXPORT`

**Comment by harrism** [comment]
Why shouldn't we mark it as breaking? All that does is put it under the "breaking changes" section of the changelog. I think for future reference it should be labeled "breaking".  Do you agree?

**Review by harrism — APPROVED** [review]

**Comment by harrism** [comment]
Hmm, looks like breathe doesn't like `RMM_EXPORT`: 

```
/__w/rmm/rmm/python/rmm/docs/librmm_docs/logging.rst:4: WARNING: Error when parsing function declaration.
If the function has no return type:
  Error in declarator or parameters-and-qualifiers
  Invalid C++ declaration: Expecting "(" in parameters-and-qualifiers. [error at 18]

    inline RMM_EXPORT spdlog::logger & logger ()
    ------------------^
If the function has a return type:
  Error in declarator or parameters-and-qualifiers
  If pointer to member declarator:
    Invalid C++ declaration: Expected '::' in pointer to member (function). [error at 33]
      inline RMM_EXPORT spdlog::logger & logger ()
      ---------------------------------^
  If declarator-id:
    Invalid C++ declaration: Expecting "(" in parameters-and-qualifiers. [error at 33]
      inline RMM_EXPORT spdlog::logger & logger ()
      ---------------------------------^
```

**Comment by wence-** [comment]
> Why shouldn't we mark it as breaking? All that does is put it under the "breaking changes" section of the changelog. I think for future reference it should be labeled "breaking". Do you agree?

Yes, done.

**Comment by wence-** [comment]
botched the merge, will look tomorrow

**Comment by vyasr** [comment]
Can we close this (and #1651) now that #1654 is resolved?

**Comment by harrism** [comment]
We want these functions explicitly marked in case the namespace export ever changes. However my per device resource PR also has these changes...

File: include/rmm/detail/export.hpp [hunk 1]
```diff
@@ -24,4 +24,5 @@
 #else
 #define RMM_EXPORT
 #define RMM_HIDDEN
+#define RMM_NAMESPACE rmm
```
Comment (wence-) [inline include/rmm/detail/export.hpp:27]: This is necessary for anyone compiling with a compiler that doesn't advertise `__GNUC__`.

**Comment by wence-** [comment]
After lots of fighting, I got doxygen working right. Unfortunately we have to reproduce the definitions of the macros in the doxyfile since it turns out that it's impossible to make `EXCLUDE_PATTERNS` work with wanting to have the doxygen preprocessor actually find the detail files that are included.

File: include/rmm/mr/device/per_device_resource.hpp [hunk 2]
```diff
@@ -90,14 +90,20 @@ namespace mr {
 
 namespace detail {
 
+// These symbols must have default visibility so that when they are
+// referenced in multiple different DSOs the linker correctly
+// determines that there is only a single unique reference to the
+// function symbols (and hence they return unique static references
+// across different DSOs).
```
Comment (harrism) [inline include/rmm/mr/device/per_device_resource.hpp:97]: Perhaps also explain that while this is subsumed by `RMM_NAMESPACE`, we want these functions explicitly annotated in case the namespace definition ever changes?

**Review by harrism — APPROVED** [review]
Approve, with one suggestion.

File: include/rmm/mr/device/per_device_resource.hpp (hunk 2 above)
Comment (wence-) [reply include/rmm/mr/device/per_device_resource.hpp]: Ah, this one slipped through the cracks. Now done.
