### PR TITLE
Deliberately leak PTDS thread_local events in stream ordered mr

### LINKED ISSUE #1371: [BUG] Initializing a non-trivial `thread_local` struct before intializing rmm in PTDS causes a cuda error at exit
**Describe the bug**
When using RMM in a target built with PTDS, initializing a `thread_local` struct with a non-default destructor before initializing stream ordered resource causes a cuda error at exit.

**Steps/Code to reproduce bug**
Apply the following changes to the pool mr tests and run `POOL_MR_PTDS_TEST`.
```diff
diff --git a/tests/mr/device/pool_mr_tests.cpp b/tests/mr/device/pool_mr_tests.cpp
index 4a234d2f..63b15f41 100644
--- a/tests/mr/device/pool_mr_tests.cpp
+++ b/tests/mr/device/pool_mr_tests.cpp
@@ -37,6 +37,32 @@ using cuda_mr     = rmm::mr::cuda_memory_resource;
 using pool_mr     = rmm::mr::pool_memory_resource<rmm::mr::device_memory_resource>;
 using limiting_mr = rmm::mr::limiting_resource_adaptor<rmm::mr::cuda_memory_resource>;
 
+class Stack {
+ public:
+  Stack() noexcept : size_(0), capacity_(0), base_(nullptr) {}
+
+  // ~Stack() noexcept { delete[] base_; }
+
+  // Breaks even with empty destructor
+  ~Stack() noexcept {}
+
+  // Works when defaulted
+  // ~Stack() noexcept = default;
+
+  size_t size_;
+  size_t capacity_;
+  int* base_;
+};
+
+static Stack& GetStack()
+{
+  // Crashes if thread_local. Works if only static
+  thread_local Stack stack_ = Stack();
+  return stack_;
+}
+
+TEST(Another, ThreadLocal) { GetStack(); }
+
 TEST(PoolTest, ThrowOnNullUpstream)
 {
   auto construct_nullptr = []() { pool_mr mr{nullptr}; };
```
The test runs to completion but segfaults at the end with the following cuda error.
```
[  PASSED  ] 11 tests.
CUDA Error detected. cudaErrorCudartUnloading driver shutting down
POOL_MR_PTDS_TEST: /home/devavret/Development/rapids/rmm/include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp:270: rmm::mr::detail::stream_ordered_memory_resource<PoolResource, FreeListType>::event_wrapper::~event_wrapper() [with PoolResource = rmm::mr::pool_memory_resource<rmm::mr::device_memory_resource>; FreeListType = rmm::mr::detail::coalescing_free_list]: Assertion `status__ == cudaSuccess' failed.
Aborted (core dumped)
```

**Expected behavior**
No CUDA error should be thrown.

**Additional Information**
This is more reliably reproducible with a debug build.

### PR DESCRIPTION
**Pull request by wence-**
## Description
An object with `thread_local` modifier has thread storage duration, its destructor (if it exists) will after the thread exits, which, on the main thread, is below `main` (https://eel.is/c++draft/basic.start.term). The CUDA runtime sets up (when the first call into the runtime is made) a teardown of the driver that runs `atexit`. Although [basic.start.term#5](https://eel.is/c++draft/basic.start.term#5) provides guarantees on the order in which these destructors are called (thread storage duration objects are destructed _before_ any `atexit` handlers run), it appears that gnu libstdc++ does not always implement this correctly (if not compiled with `_GLIBCXX_HAVE___CXA_THREAD_ATEXIT`).

Moreover (possibly consequently) it is considered undefined behaviour to call into the CUDA runtime below `main`. Hence, we cannot call `cudaEventDestroy` to deallocate our `thread_local` events. Since there are a finite number of these event (`ndevices * nparticipating_threads`), rather than attempting to destroy them we choose to leak them, thus avoiding any sequencing problems.

- Closes #1371

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rmm/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

File: include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp [hunk 1]
```diff
@@ -289,17 +268,17 @@ class stream_ordered_memory_resource : public crtp<PoolResource>, public device_
...
-
-        auto event = std::make_shared<event_wrapper>();
-        this->default_stream_events.insert(event);
-        return (events_tls[device_id.value()] = std::move(event))->event;
+      // Create a thread-local event for each device. These events are
+      // deliberately leaked since the destructor needs to call into
+      // the CUDA runtime and thread_local destructors (can) run below
+      // main: it is undefined behaviour to call into the CUDA
+      // runtime below main.
+      thread_local std::vector<cudaEvent_t> events_tls(rmm::get_num_cuda_devices());
```
Comment (harrism) [inline include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp:276]: These events are never created?

File: include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp [hunk 2]
```diff
@@ -505,10 +484,6 @@ class stream_ordered_memory_resource : public crtp<PoolResource>, public device_
   // bidirectional mapping between non-default streams and events
   std::unordered_map<cudaStream_t, stream_event_pair> stream_events_;
 
-  // shared pointers to events keeps the events alive as long as either the thread that created
-  // them or the MR that is using them exists.
-  std::set<std::shared_ptr<event_wrapper>> default_stream_events;
```
Comment (harrism) [inline include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp:510]: I don't think we can get rid of this.  This is not the same as the TLS events.

**Review by harrism — CHANGES_REQUESTED** [review]
I don't think this fix is quite right?

File: include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp (hunk 2 above)
Comment (wence-) [reply include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp:510]: The only reference in the source was in `get_event` function in the PTDS case, so it didn't seem to be necessary any more.

File: include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp (hunk 1 above)
Comment (wence-) [reply include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp:276]: On line 280, we call `cudaEventCreateWithFlags` passing `&event_tls[device]`, which creates the event I think?

**Comment by wence-** [comment]
I couldn't think of a good way to test this (though locally it fixes the issue in #1371).

File: include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp (hunk 1 above)
Comment (harrism) [reply include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp:276]: Sorry I was tired when I read this.

File: include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp (hunk 2 above)
Comment (harrism) [reply include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp:510]: Yes. It ensured that if the thread that owns the TLS exits, but the memory resource still exists, then the default stream events won't be deleted (by the TLS). We could have a memory resource shared by multiple threads using the same device.

Comment (harrism) [reply include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp:510]: But now I see that now `cudaEventCreateWithFlags` is called but `cudaEventDestroy` is never called. This "keep alive" set was only needed because of the RAII `event_wrapper`. Eliminating this is a nice side effect I hadn't thought of. :)

**Review by harrism — APPROVED** [review]
**👏 praise:** ‏ Ignore my previous review. Nice work. I like the simplification fixing this bug uncovers!

File: include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp [hunk 3]
```diff
@@ -289,17 +268,17 @@ class stream_ordered_memory_resource : public crtp<PoolResource>, public device_
...
+      // Create a thread-local event for each device. These events are
+      // deliberately leaked since the destructor needs to call into
+      // the CUDA runtime and thread_local destructors (can) run below
+      // main: it is undefined behaviour to call into the CUDA
+      // runtime below main.
+      thread_local std::vector<cudaEvent_t> events_tls(rmm::get_num_cuda_devices());
+      auto event = [device_id = this->device_id_]() {
+        if (events_tls[device_id.value()]) { return events_tls[device_id.value()]; }
+        RMM_ASSERT_CUDA_SUCCESS(
+          cudaEventCreateWithFlags(&events_tls[device_id.value()], cudaEventDisableTiming));
```
Comment (wence-) [inline include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp:280]: **suggestion**
```suggestion
          // These events are deliberately not destructed and therefore live until program exit.
          cudaEventCreateWithFlags(&events_tls[device_id.value()], cudaEventDisableTiming));
```

File: include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp (hunk 2 above)
Comment (wence-) [reply include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp:510]: I added a suggested comment at the creation event to indicate this.

File: include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp [hunk 4]
```diff
@@ -289,17 +268,17 @@ class stream_ordered_memory_resource : public crtp<PoolResource>, public device_
...
+        return events_tls[device_id.value()];
```
Comment (jrhemstad) [inline include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp:281]:
```suggestion
    auto event = [device_id = this->device_id_]() {
      auto& e = events_tls[device_id.value()];
      if (!e) {
          RMM_ASSERT_CUDA_SUCCESS(cudaEventCreateWithFlags(&e, cudaEventDisableTiming));
      }
      return e;
```

**Review by jrhemstad — APPROVED** [review]

**Comment by harrism** [comment]
@wence- if you want to make the two suggested changes above I think we can get this merged.

File: include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp [hunk 5]
```diff
@@ -289,17 +268,20 @@ class stream_ordered_memory_resource : public crtp<PoolResource>, public device_
...
+      // runtime below main.
+      thread_local std::vector<cudaEvent_t> events_tls(rmm::get_num_cuda_devices());
+    auto event = [device_id = this->device_id_]() {
+      auto& e = events_tls[device_id.value()];
+      if (!e) {
+          // These events are deliberately not destructed and therefore live until
+          // program exit.
+          RMM_ASSERT_CUDA_SUCCESS(cudaEventCreateWithFlags(&e, cudaEventDisableTiming));
+      }
+      return e;
```
Comment (wence-) [inline include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp:284]:
```suggestion
      auto event = [device_id = this->device_id_]() {
        auto& e = events_tls[device_id.value()];
        if (!e) {
            // These events are deliberately not destructed and therefore live until
            // program exit.
            RMM_ASSERT_CUDA_SUCCESS(cudaEventCreateWithFlags(&e, cudaEventDisableTiming));
        }
        return e;
```
