### PR TITLE
Remove the friend declaration with an attribute

### LINKED ISSUE #1668: [BUG] Compile error using gcc 13.2.0
**Describe the bug**
The branch-24.10 has the following compile error when built with gcc 13.2.0:
```
In file included from /home/biubiuty/biubiu/rmm/rmm/tests/mr/device/adaptor_tests.cpp:26:
/home/biubiuty/biubiu/rmm/rmm/include/rmm/mr/device/logging_resource_adaptor.hpp:292:38: error: attribute ignored [-Werror=attributes]
  292 |   friend logging_resource_adaptor<T> make_logging_adaptor(T* upstream,
      |                                      ^~~~~~~~~~~~~~~~~~~~
/home/biubiuty/biubiu/rmm/rmm/include/rmm/mr/device/logging_resource_adaptor.hpp:292:38: note: an attribute that appertains to a friend declaration that is not a definition is ignored
cc1plus: all warnings being treated as errors
make[2]: *** [tests/CMakeFiles/ADAPTOR_TEST.dir/build.make:76: tests/CMakeFiles/ADAPTOR_TEST.dir/mr/device/adaptor_tests.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1327: tests/CMakeFiles/ADAPTOR_TEST.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
b
```

**Steps/Code to reproduce bug**
Use gcc version 12.1 or newer, and follow the instruction to build RMM from source.

**Expected behavior**
No compile error.

**Environment details (please complete the following information):**
 - Environment location: Bare-metal
 - Method of RMM install: from source
 - Please run and attach the output of the `rmm/print_env.sh` script to gather relevant environment details

[print_env.txt](https://github.com/user-attachments/files/16896733/print_env.txt)

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by kingcrimsontianyu**
## Description
The `logging_resource_adaptor` has a friend declaration (which is not a definition) preceded by an attribute, whereas C++ standard requires that such [declaration must be a definition](https://eel.is/c++draft/dcl.attr.grammar#5). gcc 11.4.0 used in the dev container does not correctly identify this, but gcc 12.1 and newer are able to, and will report a compile error (converted from a warning) when building RMM:

```
an attribute that appertains to a friend declaration that is not a definition is ignored
```
This simple PR removes the friend declaration from the `logging_resource_adaptor` class. This is valid since in recent releases of RMM the friended function no longer accesses any private (or protected) data or methods of `logging_resource_adaptor`.

closes #1668 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rmm/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

File: include/rmm/mr/device/logging_resource_adaptor.hpp [hunk 1]
```diff
@@ -283,16 +283,6 @@ class logging_resource_adaptor final : public device_memory_resource {
...
-  // make_logging_adaptor needs access to private get_default_filename
-  template <typename T>
-  // NOLINTNEXTLINE(readability-redundant-declaration)
-  [[deprecated(
-    "make_logging_adaptor is deprecated in RMM 24.10. Use the logging_resource_adaptor constructor "
-    "instead.")]]
-  friend logging_resource_adaptor<T> make_logging_adaptor(T* upstream,
-                                                          std::string const& filename,
-                                                          bool auto_flush);
-
```
Comment (wence-) [inline include/rmm/mr/device/logging_resource_adaptor.hpp:295]: Is this right? To my understanding we need the friend declaration (so that `make_logging_adaptor` can access the private method. However, what we can't do is add the `[[deprecated()]]` attribute. So do we want to just delete that one line?

Comment (kingcrimsontianyu) [reply include/rmm/mr/device/logging_resource_adaptor.hpp:295]: If I didn't miss anything, `make_logging_adaptor` calls the public constructor and the public static method `get_default_filename()`, so it does not have to be a friend of `logging_resource_adaptor`. The reason it became a friend is that initially `get_default_filename()` is a private static method.

**Review by rongou — APPROVED** [review]

File: include/rmm/mr/device/logging_resource_adaptor.hpp (hunk 1 above)
Comment (wence-) [reply include/rmm/mr/device/logging_resource_adaptor.hpp:295]: Aha, thanks, I missed that aspet.

Comment (kingcrimsontianyu) [reply include/rmm/mr/device/logging_resource_adaptor.hpp:295]: Thanks for raising that question!

File: tests/CMakeLists.txt [hunk 2]
```diff
@@ -149,16 +149,16 @@ ConfigureTest(TRACKING_TEST mr/device/tracking_mr_tests.cpp GPUS 1 PERCENT 100)
 ConfigureTest(FAILURE_CALLBACK_TEST mr/device/failure_callback_mr_tests.cpp)
 
 # prefetch adaptor tests
-ConfigureTest(PREFETCH_ADAPTOR_TEST mr/device/prefetch_resource_adaptor_tests.cpp)
+ConfigureTest(PREFETCH_ADAPTOR_TEST mr/device/prefetch_resource_adaptor_tests.cpp GPUS 1 PERCENT 100)
```
Comment (harrism) [inline tests/CMakeLists.txt:152]: Were these cmake changes accidentally added? I don't think these should be in the PR.

**Review by harrism — CHANGES_REQUESTED** [review]
Thanks for the fix and for noticing that we no longer need this friend declaration!

Just wondering about the cmake test GPU configuration changes.

File: tests/CMakeLists.txt (hunk 2 above)
Comment (bdice) [reply tests/CMakeLists.txt:152]: We've had a lot of flaky test failures in RMM lately due to parallel test execution causing OOM errors. It was advised in an offline discussion to try and set some of the failing tests to use `PERCENT 100` to avoid OOM-ing.

**Review by bdice — APPROVED** [review]

File: tests/CMakeLists.txt (hunk 2 above)
Comment (bdice) [reply tests/CMakeLists.txt:152]: @harrism @kingcrimsontianyu If we don't reach consensus on doing this here, let's consider separating these changes into another PR. We do need a fix for the flaky CI failures from OOM errors.

Comment (harrism) [reply tests/CMakeLists.txt:152]: Got it.

**Review by harrism — APPROVED** [review]

**Comment by harrism** [comment]
I don't think adding a single signed commit is enough. There have to be zero unsigned commits in the history of the PR.

File: tests/CMakeLists.txt (hunk 2 above)
Comment (harrism) [reply tests/CMakeLists.txt:152]: Oh, I already submitted the merge command since we have approvals.

Comment (harrism) [reply tests/CMakeLists.txt:152]: Hmmm, `prefetch_resource_adaptor_tests.cpp` allocates at most 400KB from what I can tell.

`limiting_mr_tests.cpp` allocates 10s of MB. So also not much.

`mr/host/mr_ref_tests.cpp` allocates HOST memory at most 1GiB per test.

Why were these tests chosen to change?

**Review by harrism — CHANGES_REQUESTED** [review]
Blocking merge while we discuss the `GPUS 1 PERCENT 100` further.

**Review by bdice — APPROVED** [review]
Thanks for reverting the CMake changes for now — we can explore improving the tests in a follow-up.

File: tests/CMakeLists.txt (hunk 2 above)
Comment (kingcrimsontianyu) [reply tests/CMakeLists.txt]: As suggested, I have reverted the CMake script changes for this MR. 
PS: Also manually squashed the commits into a single signed one.

**Review by harrism — APPROVED** [review]
Thanks!
