### PR TITLE
[REVIEW] Add debug/info/trace logging and fix multithreaded replay bench

### LINKED ISSUE #431: [BUG] Multi-threaded replay benchmark broken when an allocation is freed on a different thread
**Describe the bug**

The replay benchmark parses a log for all per-thread events and collates each thread's (de)allocation events. The benchmark launches `n` threads and then replays all of those events in order on each individual thread.

When replaying the events, each event indicates if the action is an allocation or a free as well as the pointer that was allocated/freed in the logged application. This pointer is used to match corresponding allocation/free events in the log. This is accomplished by each thread maintaining an [`unordered_map` of a logged pointer to an actual allocation ](https://github.com/rapidsai/rmm/blob/30d938afe064b362e1c5b67fcefc910988f1af97/benchmarks/replay/replay.cpp#L73) made during the replay. 

This strategy is broken in two ways when the log contains an allocation made on thread `i`, but freed on another thread `j`.

First, the `unordered_map` of a logged pointer to an allocation is unique per thread. Therefore, if the allocation is made on `i`, then `j` will attempt to find a pointer that doesn't exist in its map.

Second, there is nothing to synchronize `i` and `j`, i.e., there is nothing to guarantee that `i` allocated a pointer `p` before `j` attempted to free it (assuming the above problem was resolved). 

This results in the benchmark silently failing, or crashing with a segfault. 

**Steps/Code to reproduce bug**

Run the replay benchmark with multiple threads where an allocation is created on one thread and freed on another. 

**Expected behavior**

The multi-threaded replay benchmark should be able to handle an allocation being freed on a different thread.

**Additional context**

I haven't though of how to resolve this without introducing a lot of expensive synchronization and overhead that would pollute the results of the benchmark.

### PR DESCRIPTION
**Pull request by harrism**
This PR adds debug logging using spdlog so that it is accessible from anywhere in RMM, and provides convenience macros for various levels of logging. 

Adds CMake configuration to set the default logging level OFF, and allows specifying spdlog levels
using `-DLOGGING_LEVEL=<level>` on the cmake command line, where `level` is one of [TRACE, INFO, DEBUG, WARNING, ERROR, CRITICAL].

Changing the level changes which level of logging messages are compiled in, but since spdlog's
default logging level is INFO, if you need lower-level logging, then the application must also
set spdlog's runtime logging level using `rmm::logger().set_level()` (e.g. to spdlog::level::trace).

By default the log goes to a file `rmm_log.txt` unless a filename is specified in the environment variable `RMM_DEBUG_LOG_FILENAME`.

Also replaces calls to `assert` with a new macro `RMM_LOGGING_ASSERT` which logs the reason for the assertion (only active in debug build, just like assert).

This PR also fixes replay of multithreaded logs to ensure the logs are replayed in the actual order they occured to prevent deallocations preceding their corresponding allocations.
Fixes #431.

~TODO: Add logging in more memory resources.~ We can add further logging in follow up PRs to keep this one manageable.

CC @jlowe @rongou @abellina

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

File: include/rmm/detail/error.hpp [hunk 1]
```diff
@@ -205,5 +207,22 @@ class out_of_range : public std::out_of_range {
...
+#ifdef NDEBUG
+#define RMM_LOGGING_ASSERT(_expr) (void)0
+#else
+#define RMM_LOGGING_ASSERT(_expr)                                                                 \
+  do {                                                                                            \
+    if (!(_expr)) {                                                                               \
+      RMM_LOG_CRITICAL(                                                                           \
+        "[" __FILE__ ":" RMM_STRINGIFY(__LINE__) "] Assertion " RMM_STRINGIFY(_expr) " failed."); \
+      rmm::logger().flush();                                                                      \
+      assert((_expr));                                                                            \
```
Comment (jrhemstad) [inline include/rmm/detail/error.hpp:225]: This had a similar issue to that Thrust macro bug where the `_expr` was being evaluated twice. We should only evaluate it once and reuse the result. 

```suggestion
  do {                                                                                            \
    bool const success = (_expr);
    if (!success) {                                                                               \
      RMM_LOG_CRITICAL(                                                                           \
        "[" __FILE__ ":" RMM_STRINGIFY(__LINE__) "] Assertion " RMM_STRINGIFY(_expr) " failed."); \
      rmm::logger().flush();                                                                      \
      assert(success);                                                                            \
```

File: include/rmm/detail/logger.hpp [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+
+#include <spdlog/sinks/basic_file_sink.h>
+#include <spdlog/spdlog.h>
+
+#include <iostream>
+#include <string>
+
+namespace rmm {
+
+namespace {
```
Comment (jrhemstad) [inline include/rmm/detail/logger.hpp:27]: Anonymous namespaces is headers are almost always a bug. 
```suggestion
namespace detail{
```

File: include/rmm/detail/logger.hpp [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+}  // namespace
+
+inline spdlog::logger& logger()
+{
+  bool truncate_file{true};
+  static spdlog::logger logger_(
+    "RMM",
+    std::make_shared<spdlog::sinks::basic_file_sink_mt>(default_log_filename(), truncate_file));
+  static bool initialized{false};
+  if (not initialized) {
```
Comment (jrhemstad) [inline include/rmm/detail/logger.hpp:43]: There is a race condition here. C++11 function local static initialization will guarantee that only one thread will construct `initialized`, but after that many threads can potentially enter the `if(not initialized)` branch and race in executing the contents of the branch. 

I'd suggest putting construction of the `spdlog::logger` object and the below initialization (set_pattern, etc.) into the constructor of a wrapper object. Then we can just have a function local static instance of that wrapper object, e.g.,

```
inline spdlog::logger& logger(){
   static logger_wrapper w{...};
   return w.logger();
}
```

Then you can just rely on the construct once logic of the language instead of having to keep track of an `initialized` variable and potentially have races.

File: include/rmm/mr/device/pool_memory_resource.hpp [hunk 4]
```diff
@@ -178,10 +184,17 @@ class pool_memory_resource final
...
+    RMM_LOG_INFO("[A][Stream {}][Upstream {}B]", reinterpret_cast<void*>(stream), size);
+
+    try {
+      void* p = upstream_mr_->allocate(size, stream);
+      block_type b{reinterpret_cast<char*>(p), size, true};
+      upstream_blocks_.emplace_back(b);  // TODO: with C++17 use version that returns a reference
+      return b;
+    } catch (std::exception const& e) {
+      RMM_LOG_ERROR("[A][Stream {}][Upstream {}B][FAILURE]", reinterpret_cast<void*>(stream), size);
+      throw e;
```
Comment (jrhemstad) [inline include/rmm/mr/device/pool_memory_resource.hpp:196]: This would throw a copy of the base exception instead of throwing the same exception object, i.e., you'd lose any derived object. Instead, rethrow the same exception object. 
```suggestion
      throw;
```

File: benchmarks/replay/replay.cpp [hunk 5]
```diff
@@ -215,18 +340,19 @@ int main(int argc, char** argv)
...
-    ->Unit(benchmark::kMillisecond)
-    ->Threads(num_threads);
+  // Uncomment to enable / change default log level
+  // rmm::logger().set_level(spdlog::level::trace);
+
+  if (args.count("resource") > 0) {
+    std::string mr_name = args["resource"].as<std::string>();
+    declare_benchmark(mr_name, per_thread_events, num_threads);
+  } else {
+    std::array<std::string, 4> mrs{"pool", "binning", "cuda"};
```
Comment (jrhemstad) [inline benchmarks/replay/replay.cpp:350]:
```suggestion
    std::array<std::string, 3> mrs{"pool", "binning", "cuda"};
```

File: benchmarks/replay/replay.cpp [hunk 6]
```diff
@@ -74,42 +79,128 @@ struct allocation {
...
+    : factory_{factory}, mr_{}, events_{events}, allocation_map{events.size()}, event_index{0}
+  {
+  }
+
+  /**
+   * @brief Copy construct a replay_benchmark
+   *
+   * Does not copy the mutex or the map
+   */
+  replay_benchmark(replay_benchmark const& other)
```
Comment (jrhemstad) [inline benchmarks/replay/replay.cpp:113]: Does this need a copy ctor?

File: benchmarks/replay/replay.cpp [hunk 7]
```diff
@@ -74,42 +79,128 @@ struct allocation {
...
+      if (num_leaked > 0)
+        std::cout << "LOG shows leak of " << num_leaked << " allocations of " << total_leaked
+                  << " total bytes\n";
+      allocation_map.clear();
+      mr_.reset();
+    }
+  }
 
+  /// Run the replay benchmark
+  void BenchmarkCase(::benchmark::State& state) override
```
Comment (jrhemstad) [inline benchmarks/replay/replay.cpp:177]: I can't find `BenchmarkCase` documented anywhere and am not sure what it is for as opposed to just using the `operator()` directly. AFAIK, you can pass any callable object to `RegisterBenchmark`.

File: benchmarks/replay/replay.cpp [hunk 8]
```diff
@@ -74,42 +79,128 @@ struct allocation {
...
+    return allocation{};
+  }
+
+  /// Create the memory resource shared by all threads before the benchmark runs
+  void SetUp(const ::benchmark::State& state) override
+  {
+    if (state.thread_index == 0) {
+      rmm::logger().log(spdlog::level::info, "------ Start of Benchmark -----");
+      mr_ = factory_();
+    }
```
Comment (jrhemstad) [inline benchmarks/replay/replay.cpp:151]: Why not just put this logic in the `replay_benchmark` ctor? That way you don't have to do the check against the `thread_index`. Only one instance of the fixture object is constructed and shared by all threads.

File: benchmarks/replay/replay.cpp [hunk 9]
```diff
@@ -74,42 +79,128 @@ struct allocation {
...
 
+    using namespace std::chrono_literals;
+
     for (auto _ : state) {
-      std::for_each(my_events.begin(), my_events.end(), [&allocation_map, &state, this](auto e) {
+      std::for_each(my_events.begin(), my_events.end(), [&state, this](auto e) {
+        // ensure correct ordering between threads
+        while (event_index < e.index) {
+          std::this_thread::sleep_for(2us);
+        }
```
Comment (jrhemstad) [inline benchmarks/replay/replay.cpp:188]: My suspicion is that it would be better to use a `std::condition_variable` here.

Comment (jrhemstad) [reply benchmarks/replay/replay.cpp:188]: Something like this: https://godbolt.org/z/rxqGWE

File: include/rmm/detail/error.hpp (hunk 1 above)
Comment (harrism) [reply include/rmm/detail/error.hpp:225]: Yeah I realized that the other day when the Thrust issue was found. Will fix.

File: benchmarks/replay/replay.cpp (hunk 8 above)
Comment (harrism) [reply benchmarks/replay/replay.cpp:151]: THe problem is the replay_benchmarks ctor is called when you register the benchmark, and the dtor is not called until after ALL the benchmarks have run. So you end up constructing all the MRs you are benchmarking first, then running the benchmarks, then destroying them. If you have a pool_mr and a binning_mr, then you effectively use up all the GPU memory before any benchmark runs, and the result is OOM during the first benchmark of one of those MRs.  This is the whole reason for all the shenanigans with the fixture. 

Google benchmark is not well designed for this case. It took me the better part of a day of reading their undocumented code to figure out a workaround.

File: benchmarks/replay/replay.cpp (hunk 6 above)
Comment (harrism) [reply benchmarks/replay/replay.cpp:113]: Yes because of the mutex. Won't compile without it.

File: benchmarks/replay/replay.cpp (hunk 7 above)
Comment (harrism) [reply benchmarks/replay/replay.cpp:177]: `BenchmarkFixture::Run` is basically `SetUp(); BenchmarkCase(state); TearDown();`.   My operator() calls Run. I can change it so that the operator just calls setup and teardown I guess.  In that case it doesn't even need to be a fixture...

File: benchmarks/replay/replay.cpp (hunk 8 above)
Comment (harrism) [reply benchmarks/replay/replay.cpp:151]: Also each benchmark may be run multiple times, and you don't want to reuse the pool (or time creation of the pool) across runs.

File: benchmarks/replay/replay.cpp (hunk 7 above)
Comment (harrism) [reply benchmarks/replay/replay.cpp]: Fixed.

File: benchmarks/replay/replay.cpp (hunk 9 above)
Comment (harrism) [reply benchmarks/replay/replay.cpp]: Thanks!  Done.

**Comment by harrism** [comment]
Thanks @jrhemstad I addressed all of your feedback (except the benchmark construction timing).

File: benchmarks/replay/replay.cpp (hunk 6 above)
Comment (jrhemstad) [reply benchmarks/replay/replay.cpp:113]: I don't understand. Where is `replay_benchmark` being copied that it needs a copy ctor. `std::mutex` is neither copyable or movable, so I understand why the default copy ctor would fail, but I wouldn't think `replay_benchmark` should ever need to be copied. Instead I'd explicitly delete `replay_benchmarks` copy and move ctors.

File: benchmarks/replay/replay.cpp [hunk 10]
```diff
@@ -75,40 +80,128 @@ struct allocation {
...
+  }
+
+  /// Run the replay benchmark
+  void operator()(::benchmark::State& state)
+  {
+    SetUp(state);
 
     auto const& my_events = events_.at(state.thread_index);
 
+    using namespace std::chrono_literals;
```
Comment (jrhemstad) [inline benchmarks/replay/replay.cpp:181]:
```suggestion
```

File: include/rmm/mr/device/pool_memory_resource.hpp [hunk 11]
```diff
@@ -178,10 +184,17 @@ class pool_memory_resource final
...
-    return b;
+    RMM_LOG_INFO("[A][Stream {}][Upstream {}B]", reinterpret_cast<void*>(stream), size);
+
+    try {
+      void* p = upstream_mr_->allocate(size, stream);
+      block_type b{reinterpret_cast<char*>(p), size, true};
+      upstream_blocks_.emplace_back(b);  // TODO: with C++17 use version that returns a reference
+      return b;
+    } catch (std::exception const& e) {
+      RMM_LOG_ERROR("[A][Stream {}][Upstream {}B][FAILURE]", reinterpret_cast<void*>(stream), size);
```
Comment (jrhemstad) [inline include/rmm/mr/device/pool_memory_resource.hpp:195]: Do you want to include the `e.what()` in the logged failure message?

**Comment by harrism** [comment]
Please do not merge. There appears to be a problem with the `fmt` lib included in spdlog and libcudf compilation.

**Comment by harrism** [comment]
This PR introduces a libcudf build error that I have root-caused to `fmt` lib: https://github.com/fmtlib/fmt/issues/1850. I have a fix: https://github.com/fmtlib/fmt/pr/1851 but that needs to get incorporated into spdlog: https://github.com/gabime/spdlog/issues/1661

So I think I will need to patch the file (2-character fix) locally as part of the present PR rather than wait...

File: include/rmm/mr/device/pool_memory_resource.hpp (hunk 11 above)
Comment (harrism) [reply include/rmm/mr/device/pool_memory_resource.hpp]: Done

File: benchmarks/replay/replay.cpp (hunk 10 above)
Comment (harrism) [reply benchmarks/replay/replay.cpp]: Done

File: benchmarks/replay/replay.cpp (hunk 6 above)
Comment (harrism) [reply benchmarks/replay/replay.cpp:113]: `template <class Lam> benchmark::RegisterBenchmark(const char*, Lam&&)` creates an instance of this class, which invokes the copy ctor of the `Lam` that is passed to it.

```
#ifdef BENCHMARK_HAS_CXX11
template <class Lambda>
class LambdaBenchmark : public Benchmark {
 public:
  virtual void Run(State& st) { lambda_(st); }

 private:
  template <class OLambda>
  LambdaBenchmark(const char* name, OLambda&& lam)
      : Benchmark(name), lambda_(std::forward<OLambda>(lam)) {}

  LambdaBenchmark(LambdaBenchmark const&) = delete;

 private:
  template <class Lam>
  friend Benchmark* ::benchmark::RegisterBenchmark(const char*, Lam&&);

  Lambda lambda_;
};
#endif
```
https://github.com/google/benchmark/blob/4475ff6b8a7a4077d7492b76ef5278a3dc53a2e4/include/benchmark/benchmark.h#L1017-L1036

Comment (harrism) [reply benchmarks/replay/replay.cpp]: My bad, it invokes the move ctor. I have now replaced this copy ctor with a move ctor and explicitly deleted the copy ctor.

**Comment by harrism** [comment]
Turns out there's no bug in `fmt`, it's in our copy of `libcudacxx` (already fixed in mainline libcudacxx included in CUDA toolkit). I put in a better (simpler) workaround into this PR, which can be removed once libcudacxx is available on github so we can depend on it.

**Review by jrhemstad — APPROVED** [review]

File: benchmarks/utilities/log_parser.hpp [hunk 12]
```diff
@@ -80,6 +83,35 @@ inline std::ostream& operator<<(std::ostream& os, event const& e)
...
+ * is in timestamp order even for multithreaded logs.
+ * @note This function can be simplified with C++20 and later.
+ *
+ * @param str_time The input time in format "HH:MM:SS:us" where us is a 6 digits microseconds part
+ * of the current second. (This is the format rmm::mr::logging_resource_adaptor outputs)
+ * @return std::chrono::time_point<std::chrono::system_clock> Converted time point.
+ */
+inline std::chrono::time_point<std::chrono::system_clock> parse_time(std::string const& str_time)
+{
+  std::size_t current, previous = 0;
```
Comment (cwharris) [inline benchmarks/utilities/log_parser.hpp:99]: `previous` is never updated, is this intentional?

File: CMakeLists.txt [hunk 13]
```diff
@@ -170,6 +170,22 @@ if(USE_NVTX)
...
+
+if(NOT LOGGING_LEVEL)
+    message(STATUS "Setting logging level to '${DEFAULT_LOGGING_LEVEL}' since none specified.")
+    set(LOGGING_LEVEL "${DEFAULT_LOGGING_LEVEL}" CACHE
+      STRING "Choose the logging level." FORCE)
+    # Set the possible values of build type for cmake-gui
+    set_property(CACHE LOGGING_LEVEL PROPERTY STRINGS
+        "TRACE" "DEBUG" "INFO" "WARN" "ERROR" "CRITICAL" "OFF")
+else()
+message(STATUS "Setting logging level to '${LOGGING_LEVEL}'")
```
Comment (cwharris) [inline CMakeLists.txt:184]:
```suggestion
    message(STATUS "Setting logging level to '${LOGGING_LEVEL}'")
```

File: include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp [hunk 14]
```diff
@@ -304,7 +317,7 @@ class stream_ordered_memory_resource : public crtp<PoolResource>, public device_
    */
   block_type get_block(size_t size, stream_event_pair stream_event)
   {
-    // Try to find a satisfactory block in free list for the same stream (no sync required)
+    // Try to find a satisfactory block in free list for the  same stream (no sync required)
```
Comment (cwharris) [inline include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp:320]:
```suggestion
    // Try to find a satisfactory block in free list for the same stream (no sync required)
```

File: include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp [hunk 15]
```diff
@@ -313,10 +326,12 @@ class stream_ordered_memory_resource : public crtp<PoolResource>, public device_
 
     // Otherwise try to find a block associated with another stream
     block_type b = get_block_from_other_stream(size, stream_event);
-    if (b.is_valid()) return b;
+    if (b.is_valid()) { return b; }
```
Comment (cwharris) [inline include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp:329]: :raised_hands: :1st_place_medal: :pray:

File: include/rmm/detail/error.hpp [hunk 16]
```diff
@@ -205,5 +207,25 @@ class out_of_range : public std::out_of_range {
...
     assert(status__ == cudaSuccess);                                            \
-  } while (0);
+  } while (0)
+#endif
+
+/**
+ * @brief Assertion that logs a CRITICAL log message on failure.
+ */
+#ifdef NDEBUG
+#define RMM_LOGGING_ASSERT(_expr) (void)0
```
Comment (cwharris) [inline include/rmm/detail/error.hpp:217]: I've never thought to ask... is it bad practice to assert in debug builds?

**Review by cwharris — CHANGES_REQUESTED** [review]

File: include/rmm/mr/device/logging_resource_adaptor.hpp [hunk 17]
```diff
@@ -19,9 +19,16 @@
 
 #include <rmm/detail/error.hpp>
 
+// If using GCC, temporary workaround for older libcudacxx defining _LIBCPP_VERSION
+// undefine it before including spdlog, due to fmtlib checking if it is defined
+// TODO: remove once libcudacxx is on Github and RAPIDS depends on it
+#ifdef __GNUG__
+#undef _LIBCPP_VERSION
```
[the remark this answers is not in the document]
Comment (harrism) [reply include/rmm/mr/device/logging_resource_adaptor.hpp:26]: No. This is defined by clangs libc++, which we don't use (GCC's is libstdc++). It's an accident that it gets defined by the version of libcudacxx that we use, because it is based on libc++. THe latest libcudacxx fixes this, but it's only available in the CUDA 11 TK and later, so we can't use it. We are waiting for libcudacxx to go to Github so we can use it on earlier CUDA versions.

File: include/rmm/detail/logger.hpp [hunk 18]
```diff
@@ -0,0 +1,78 @@
...
+#include <iostream>
+#include <string>
+
+namespace rmm {
+
+namespace detail {
+
+inline std::string default_log_filename()
+{
+  auto filename = std::getenv("RMM_DEBUG_LOG_FILE");
```
[the remark this answers is not in the document]
Comment (harrism) [reply include/rmm/detail/logger.hpp:37]: Yes, will do.

File: include/rmm/detail/logger.hpp [hunk 19]
```diff
@@ -0,0 +1,78 @@
...
+struct logger_wrapper {
+  spdlog::logger logger_;
+
+  logger_wrapper()
+    : logger_{"RMM",
+              std::make_shared<spdlog::sinks::basic_file_sink_mt>(
+                default_log_filename(), true  // truncate file
+                )}
+  {
+    logger_.set_pattern("[%l][%t][%H:%M:%S:%f] %v");
```
[the remark this answers is not in the document]
Comment (harrism) [reply include/rmm/detail/logger.hpp:51]: I don't understand why you can't sort by thread ID with the existing format?

File: include/rmm/detail/error.hpp (hunk 16 above)
Comment (harrism) [reply include/rmm/detail/error.hpp:217]: Confusing question. Assert should be a no-op in non-debug builds, which is what this does.

File: include/rmm/detail/logger.hpp (hunk 19 above)
[the remark this answers is not in the document]
Comment (cwharris) [reply include/rmm/detail/logger.hpp:51]: First, my suggestion is formatted incorrectly. The format I had in mind is:
```
[%t][%H:%M:%S:%f][%l] %v
```
It would be nice to open a log file in a text editor and "sort by lines ascending" to group the logs by thread. For that to work, the thread id would need to be printed first. The second part would need to be the timestamp, otherwise the logs would get out of order, even within a specific thread id. Therefore, the log level would need to be last. Since everything prior to the log level is fixed width, you also end up with a nice visual alignment.

```
[1232][23:59:58:056789][debug]
```

File: benchmarks/utilities/log_parser.hpp (hunk 12 above)
Comment (harrism) [reply benchmarks/utilities/log_parser.hpp]: Fixed.

File: include/rmm/detail/logger.hpp (hunk 19 above)
[the remark this answers is not in the document]
Comment (harrism) [reply include/rmm/detail/logger.hpp:59]: In my experience grouping by thread has not been useful. You need to see what is happening in time order due to multiple threads using a resource. That said, I guess this change won't hurt anything.  I'll fix the visual alignment with an explicit width for the level.

**Review by cwharris — APPROVED** [review]
lgtm.

fyi, the log format suggestion was just an idea. I don't know how useful it would be in practice. :+1:

File: include/rmm/detail/logger.hpp (hunk 18 above)
[the remark this answers is not in the document]
Comment (harrism) [reply include/rmm/detail/logger.hpp:45]: Added to readme and doxygen.

File: include/rmm/detail/logger.hpp (hunk 19 above)
[the remark this answers is not in the document]
Comment (harrism) [reply include/rmm/detail/logger.hpp]: Done.

**Comment by harrism** [comment]
> lgtm.
> 
> fyi, the log format suggestion was just an idea. I don't know how useful it would be in practice. +1

Thanks for the review!

File: include/rmm/mr/device/logging_resource_adaptor.hpp (hunk 17 above)
[the remark this answers is not in the document]
Comment (trxcllnt) [reply include/rmm/mr/device/logging_resource_adaptor.hpp:26]: Shouldn't we change this macro name in our freestanding fork?
