### PR TITLE
fix use-after-free in `tracking_resource_adaptor`

### LINKED ISSUE #1965: [BUG] use-after-free in `tracking_resource_adaptor.hpp`
In `do_deallocate`, erasing from `allocations_` invalidates all iterators, so dereferencing `found` is Undefined Behaviour. In practice, we're seeing completely messed up tracking.

### PR DESCRIPTION
**Pull request by legrosbuffle**
Erasing from `allocations_` invalidates all iterators, so dereferencing `found` is Undefined Behaviour. In practice, we're seeing completely messed up tracking.

closes #1965

### CODE REVIEW

File: cpp/include/rmm/mr/device/tracking_resource_adaptor.hpp [hunk 1]
```diff
@@ -244,10 +244,10 @@ class tracking_resource_adaptor final : public device_memory_resource {
           bytes,
           this->allocations_.size());
       } else {
-        allocations_.erase(found);
-
         auto allocated_bytes = found->second.allocation_size;
```
Comment (bdice) [inline cpp/include/rmm/mr/device/tracking_resource_adaptor.hpp]: While we're here, let's make this const.
```suggestion
        auto const allocated_bytes = found->second.allocation_size;
```

**Review by bdice — APPROVED** [review]
Thank you! This looks fine to me.
