### PR TITLE
Properly handle cudaMemHandleTypeNone and cudaErrorInvalidValue in is_export_handle_type_supported

### LINKED ISSUE #1054: [BUG] Driver 460.58 => dynamic_load_runtime.hpp:139: cudaErrorInvalidValue invalid argument
**Describe the bug**
```
0:23:56  [ERROR] testCudaAsyncMemoryResourceSize  Time elapsed: 0.002 s  <<< ERROR!
10:23:56  ai.rapids.cudf.CudfException: CUDA error at: /home/jenkins/agent/workspace/spark-rapids-jni_submodule-sync-pre_release/thirdparty/cudf/cpp/build/_deps/rmm-src/include/rmm/detail/dynamic_load_runtime.hpp:139: cudaErrorInvalidValue invalid argument
10:23:56  	at ai.rapids.cudf.Rmm.initializeInternal(Native Method)
```

per https://github.com/NVIDIA/spark-rapids-jni/issues/287#issuecomment-1140579015

**Steps/Code to reproduce bug**
On a Linux box with Driver 460.58, 

Either clone https://github.com/NVIDIA/spark-rapids-jni
and run 
```
./build/build-in-docker verify -Dtest=testCudaAsyncMemoryResourceSize
```

or clone rapidsai/cudf and run:
```
./build.sh  cudfjar
```

**Expected behavior**
The test should pass. 
This regression is presumably triggered by #1051

**Environment details (please complete the following information):**
Host Linux with  460.58 
centos7 docker based on CUDA 11.5
(cc @pxLi  for more details)
 
**Additional context**
NVIDIA/spark-rapids-jni#287

### PR DESCRIPTION
**Pull request by gerashegalov**
- [x] Intercept `cudaErrorInvalidValue` returned from `cudaDeviceGetAttribute` to return `false` from `is_export_handle_type_supported ` 
- [x]  Return true from is_export_handle_type_supported for `cudaMemHandleTypeNone`

Co-authored-by: @jrhemstad 
Co-authored-by: @harrism 

Closes #1054

Signed-off-by: Gera Shegalov <gera@apache.org>

### CODE REVIEW

**Review by harrism — APPROVED** [review]
Thanks for the fix!

File: include/rmm/detail/dynamic_load_runtime.hpp [hunk 1]
```diff
@@ -136,9 +136,16 @@ struct async_alloc {
...
-                                        rmm::detail::current_device().value()));
+    auto const result = cudaDeviceGetAttribute(&supported_handle_types_bitmask,
+                                               cudaDevAttrMemoryPoolSupportedHandleTypes,
+                                               rmm::detail::current_device().value());
+
+    // Don't throw on cudaErrorInvalidValue
+    auto const unsupported_runtime = (result == cudaErrorInvalidValue);
+    if (unsupported_runtime) return false;
+    // throw any other error that may have occurred
+    RMM_CUDA_TRY(result);
```
Comment (harrism) [inline include/rmm/detail/dynamic_load_runtime.hpp:147]: We should change this so it always returns true for `cudaMemHandleTypeNone` even if the driver is older than CUDA 11.3. (when `cudaDevAttrMemoryPoolSupportedHandleTypes` was introduced).

```suggestion
    if (cudaMemHandleTypeNone != handle_type) {
        auto const result = cudaDeviceGetAttribute(&supported_handle_types_bitmask,
                                                   cudaDevAttrMemoryPoolSupportedHandleTypes,
                                                   rmm::detail::current_device().value());

        // Don't throw on cudaErrorInvalidValue
        auto const unsupported_runtime = (result == cudaErrorInvalidValue);
        if (unsupported_runtime) return false;
        // throw any other error that may have occurred
        RMM_CUDA_TRY(result);
    }
```

**Review by harrism — CHANGES_REQUESTED** [review]
Suggesting a more complete fix.

**Review by harrism — APPROVED** [review]

**Comment by harrism** [comment]
@gerashegalov please confirm this fixes #1054 before we merge. Thanks!

**Comment by pxLi** [comment]
may I ask will this be cherry-picked to 22.06?

**Comment by gerashegalov** [comment]
> please confirm this fixes #1054 before we merge. Thanks!

Fix confirmed with https://github.com/rapidsai/cudf/compare/branch-22.08...gerashegalov:rmmTest?expand=1#diff-707bbf4bad4194f1803f3586af0611546f6064a20561f68e34f74f30d2ec4f55L20-R27

**Comment by gerashegalov** [comment]
@gpucibot merge

**Comment by harrism** [comment]
@gpucibot merge
