### PR TITLE
Remove align-up on base allocations.

### LINKED ISSUE #2116: [BUG] `rmm::align_up` is being used incorrectly
## The Problem

RMM's `device_memory_resource` and related classes are using `rmm::align_up()` to round up allocation sizes before passing them to underlying allocators. The intent was to provide aligned allocations, but **this approach is flawed**.

### Why This Doesn't Work

Calling `rmm::align_up(bytes, alignment)` increases the allocation size, but it does **not** guarantee that the returned pointer will be aligned. Alignment is a property of the pointer's memory address, not the allocation size.

For example:
```cpp
// Before (incorrect approach)
void* ptr = do_allocate(rmm::align_up(1000, 256), stream);
// This allocates 1024 bytes (1000 rounded up to next 256-byte multiple)
// But the pointer 'ptr' might be at address 0x12340001 - not aligned!
```

The extra padding bytes at the end serve no purpose. They don't make the returned pointer more aligned - they just waste memory.

## Example

In `cpp/include/rmm/mr/device/device_memory_resource.hpp`, the alignment parameter was being applied incorrectly. It computed padding bytes rather than actually aligning the base pointer:

```cpp
void* allocate(std::size_t bytes, std::size_t alignment)
{
  return do_allocate(rmm::align_up(bytes, alignment), cuda_stream_view{});
}
```

The same pattern appeared in other allocate/deallocate functions.

## Impact

The changes to Python tests in #2114 reveal the effect of this bug. Allocations were being artificially inflated:

```python
# test_rmm.py - Tracking resource test
# Before: 10 allocations of 1000 bytes each = 10,080 bytes (due to align_up)
# After:  10 allocations of 1000 bytes each = 10,000 bytes (actual request)
assert mr.get_allocated_bytes() == 5000  # was 5040

# test_statistics.py - Statistics test
# Before: 1000 bytes aligned up to 1008 bytes
# After:  1000 bytes = 1000 bytes
assert stats.current_bytes == 10  # was 16
assert stats.total_bytes == 20    # was 32
```

These tests show that 1000-byte allocations were being rounded up to 1008 bytes, wasting 8 bytes per allocation without providing any alignment benefit.

## What Actually Provides Alignment?

CUDA memory allocations (via `cudaMalloc` and similar functions) already return pointers with **256-byte alignment** by default. This is guaranteed by the CUDA runtime.

Other memory resource implementations must provide 256-byte alignment as a part of the memory resource implementation contract.
Suballocating adaptors such as the pool and arena adaptors must account for 256-byte alignment in their suballocations.

From the updated documentation in `device_memory_resource.hpp:291-293` in #2114:

```cpp
/**
 * @brief Allocates memory of size at least \p bytes.
 *
 * The returned pointer will have 256 byte alignment regardless of the value
 * of alignment. Higher alignments must use the aligned_resource_adaptor.
 */
```

The alignment parameter in these functions is informational - it tells the allocator what alignment the caller expects, but the base allocator always provides 256-byte alignment.

Allowable inputs for the alignment are any power of 2 that is less than or equal to 256. A related bug was fixed in #2107 for host memory resources.

### For Base Allocations (≤256 bytes alignment)

Remove all `rmm::align_up()` calls when passing sizes to `do_allocate()` and `do_deallocate()`. The underlying CUDA allocators already provide 256-byte alignment.

```cpp
// Correct approach
void* allocate(std::size_t bytes, std::size_t alignment)
{
  RMM_EXPECTS(alignment <= rmm::CUDA_ALLOCATION_ALIGNMENT &&
              rmm::is_supported_alignment(alignment),
              "Alignment must be less than or equal to 256 and a power of two");
  return do_allocate(bytes, cuda_stream_view{});
}
```

### For Higher Alignments (>256 bytes)

Users who need alignment greater than 256 bytes must use `aligned_resource_adaptor`, which properly aligns pointers by:
1. Over-allocating memory
2. Adjusting the returned pointer to the desired alignment boundary
3. Storing offset information to allow proper deallocation

## Summary

- **Problem**: `align_up()` on sizes adds useless padding without aligning pointers
- **Root cause**: Alignment is about pointer addresses, not allocation sizes
- **Impact**: Wasted memory with no benefit (e.g., 1000 bytes → 1008 bytes)
- **Solution**: Remove `align_up()` calls and rely on CUDA's 256-byte guarantee, implemented in #2114
- **For >256 byte alignment**: Use `aligned_resource_adaptor`

### PR DESCRIPTION
**Pull request by bdice**
## Description
Resolves #2116.

This is breaking because allocation sizes may change due to the removed padding. However, allocations are still guaranteed to be aligned to 256 bytes (the CUDA alignment requirement).

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rmm/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by ttnghia — APPROVED** [review]

File: cpp/include/rmm/mr/device/pool_memory_resource.hpp [hunk 1]
```diff
@@ -328,9 +328,8 @@ class pool_memory_resource final
   {
     if (maximum_pool_size_.has_value()) {
       auto const unaligned_remaining = maximum_pool_size_.value() - pool_size();
-      using rmm::align_up;
-      auto const remaining    = align_up(unaligned_remaining, rmm::CUDA_ALLOCATION_ALIGNMENT);
-      auto const aligned_size = align_up(size, rmm::CUDA_ALLOCATION_ALIGNMENT);
+      auto const remaining    = rmm::align_up(unaligned_remaining, rmm::CUDA_ALLOCATION_ALIGNMENT);
```
Comment (harrism) [inline cpp/include/rmm/mr/device/pool_memory_resource.hpp:331]: **🤓 nitpick (non-blocking):** ‏I don't understand the need for this change. You add one line in order to eliminate 4 characters on two other lines. By this logic, you should also add `using rmm::CUDA_ALLOCATION_ALIGNMENT` to eliminate 4 more characters on each of those lines? :)

Comment (bdice) [reply cpp/include/rmm/mr/device/pool_memory_resource.hpp:331]: I didn't like that this was the only place in the codebase with a `using` statement for this. Everything else in the codebase was specifying the `rmm::` namespace, and that's my style preference. Reasons for that weak preference:
- it's easier to tell where functions come from (this is a free function from RMM, and it's less likely to confuse for a method of the current object, etc.)
- it makes it easier to copy code from RMM into other projects if the namespaces are specified

Comment (harrism) [reply cpp/include/rmm/mr/device/pool_memory_resource.hpp:331]: Hey wow, I completely misread this. I read the old code as the new code, and wondered why you were adding a `using`. We are on the same page.
