### PR TITLE
Fix handling of cudaStreamPerThread when not compiled for PTDS

### LINKED ISSUE #535: [BUG] Even CUDA_API_PER_THREAD_DEFAULT_STREAM is not set，@stream may still equal to cudaStreamPerThread
https://github.com/rapidsai/rmm/blob/9bb169430d42feb0e999ba0543ec1b0144471643/include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp#L269

Even CUDA_API_PER_THREAD_DEFAULT_STREAM is not set，@stream may still equal to cudaStreamPerThread (i remember the user can use  cudaStreamPerThread explicitly)

https://developer.nvidia.com/blog/gpu-pro-tip-cuda-7-streams-simplify-concurrency/
Starting in CUDA 7 you can also explicitly access the per-thread default stream using the handle cudaStreamPerThread, and you can access the legacy default stream using the handle cudaStreamLegacy

### PR DESCRIPTION
**Pull request by harrism**
Fixes #535 

Now treats `cudaStreamPerThread` with a separate event per thread even if not compiled with `-DPER_THREAD_DEFAULT_STREAM=ON`.

### CODE REVIEW

**Review by codereport — APPROVED** [review]
LGTM

File: include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp [hunk 1]
```diff
@@ -286,19 +281,24 @@ class stream_ordered_memory_resource : public crtp<PoolResource>, public device_
...
     }
-#else
+#ifndef CUDA_API_PER_THREAD_DEFAULT_STREAM
     // We use cudaStreamLegacy as the event map key for the default stream for consistency between
     // PTDS and non-PTDS mode. In PTDS mode, the cudaStreamLegacy map key will only exist if the
     // user explicitly passes it, so it is used as the default location for the free list
     // at construction. For consistency, the same key is used for null stream free lists in non-PTDS
     // mode.
-    if (cudaStreamDefault == stream) { stream = cudaStreamLegacy; }
+    else if (cudaStreamDefault == stream) {
```
Comment (cwharris) [inline include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp:299]:
```suggestion
    if (cudaStreamDefault == stream) {
```

**Review by cwharris — APPROVED** [review]
lgtm

File: include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp (hunk 1 above)
Comment (harrism) [reply include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp:299]: This is definitely an else if.
