### PR TITLE
Fix bug, improve testing for pinned_host_memory_resource, and error on non-power-of-2 alignments in host memory resources

### LINKED ISSUE #2108: [BUG] pinned_host_memory_resource change to derive from device_memory_resource causes segfault in libcudf
**Describe the bug**
Changes in #2102 caused segfaults in libcudf tests `UTILITIES_TEST` and `JSON_TESTS`
https://github.com/rapidsai/cudf/actions/runs/18855716203/job/53804884204?pr=20374#step:10:2621

### PR DESCRIPTION
**Pull request by bdice**
### Fix handling of zero-byte deallocation
Fixes #2108. Allocating zero bytes with the `pinned_host_memory_resource` gives `nullptr`, as with most other memory resources, but the deallocation logic did not handle this case correctly, resulting in a segfault.

### Changes for bad alignments (breaking)
As a part of expanding the tests for `pinned_host_memory_resource`, I also fixed some tests for non-power-of-two alignments in host memory resources, which should not be allowed (neither `std::pmr::memory_resource` nor CCCL's MR design allow this). Example of C++ STL behavior: https://godbolt.org/z/dcd45rTvT

The previous behavior was to ignore the user value and instead use `std::max_align_t`. The new behavior is to raise `rmm::bad_alloc`.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rmm/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

File: cpp/tests/mr/host/mr_ref_tests.cpp
Comment (bdice) [inline cpp/tests/mr/host/mr_ref_tests.cpp:1]: These tests will be reworked pretty heavily as a part of #2103. However, for the immediate term, I want some coverage that `pinned_host_memory_resource` works with `host_resource_ref`. That concept will not be going away when the host MR implementations are deprecated and removed, because some resources are both device-accessible and host-accessible.

File: cpp/include/rmm/detail/aligned.hpp [hunk 1]
```diff
@@ -92,14 +92,16 @@ void aligned_host_deallocate(void* ptr,
 {
   assert(rmm::is_supported_alignment(alignment));
 
-  // Get offset from the location immediately prior to the aligned pointer
-  // NOLINTNEXTLINE
-  std::ptrdiff_t const offset = *(reinterpret_cast<std::ptrdiff_t*>(ptr) - 1);
+  if (ptr != nullptr) {
```
Comment (bdice) [inline cpp/include/rmm/detail/aligned.hpp:95]: This nullptr check was missing, and I think that is the root cause of the segfaults that were observed in #2108.

File: cpp/tests/mr/host/mr_ref_tests.cpp [hunk 2]
```diff
@@ -258,6 +281,16 @@ TEST(PinnedResource, isPinned)
...
+
+TEST(PinnedHostResource, isPinned)
+{
+  rmm::mr::pinned_host_memory_resource mr;
+  rmm::host_resource_ref ref{mr};
+  void* ptr{nullptr};
+  EXPECT_NO_THROW(ptr = ref.allocate_sync(100));
+  EXPECT_TRUE(is_pinned_memory(ptr));
+  EXPECT_NO_THROW(ref.deallocate_sync(ptr, 100));
+}
```
Comment (davidwendt) [inline cpp/tests/mr/host/mr_ref_tests.cpp:285]: I was expecting to see a test for allocating 0 bytes as per the PR description.

Comment (bdice) [reply cpp/tests/mr/host/mr_ref_tests.cpp:285]: That is covered by testing in `cpp/tests/mr/device/mr_ref_test.hpp`. I can check on the coverage of this file too.

Comment (bdice) [reply cpp/tests/mr/host/mr_ref_tests.cpp:285]: Yes, it's now covered by this test. https://github.com/rapidsai/rmm/blob/66c7afdd274c0e43c101432e2b9faaac1dd1b4df/cpp/tests/mr/host/mr_ref_tests.cpp#L89-L94

**Review by rongou — APPROVED** [review]

**Comment by bdice** [comment]
I’m going to merge this once CI passes so that we can get cudf CI unblocked. Happy to work on any follow-up items reviewers identify.
