### PR TITLE
Error if LIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE is not defined.

### LINKED ISSUE #1783: [FEA] RMM error is unclear when `LIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE` is not provided
Currently, RMM uses experimental features from libcudacxx. We define this in CMake (https://github.com/rapidsai/rmm/blob/c1ccdadb7f3b2677fb3f0419342fb9946bfc5d08/CMakeLists.txt#L104) but not all users of RMM are consuming it via CMake (some people use Makefiles, etc.).

The error that users see looks like this:
```
/home/myuser/include/rmm/mr/device/device_memory_resource.hpp:312:65: error: 'cuda::mr' has not been declared
  312 |   friend void get_property(device_memory_resource const&, cuda::mr::device_accessible) noexcept {}
```

RMM should detect this case at compile time and explicitly issue a message about requiring `LIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE` to be defined.

Maybe something like:
```cpp
#ifndef LIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE
#error "LIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE must be defined to use RMM memory resources."
#endif
```
would suffice.

Alternatively we could explore enabling this definition in the RMM C++ code (if it's not defined).

### PR DESCRIPTION
**Pull request by bdice**
## Description
Closes #1783.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rmm/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

File: include/rmm/detail/cuda_memory_resource.hpp [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+#pragma once
+
+// Check if LIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE is defined
+#ifndef LIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE
+#error \
+  "RMM requires LIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE to be defined. This is typically done by the build system. If you're seeing this error, you may be using a custom build setup that doesn't define this flag. Please add -DLIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE to your compiler flags."
```
Comment (bdice) [inline include/rmm/detail/cuda_memory_resource.hpp:21]:
```suggestion
  "RMM requires LIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE to be defined. Please add -DLIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE to the compiler flags (this is done automatically when using RMM via CMake)."
```

File: tests/libcudacxx_flag_test/libcudacxx_flag_test.sh [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+# Try to compile the file without defining LIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE
+if g++ -std=c++17 -I"${RMM_INCLUDE_DIR}" libcudacxx_flag_test.cpp -o libcudacxx_flag_test 2> "${ERROR_FILE}"; then
+  echo "Test failed: Compilation succeeded when it should have failed"
+  exit 1
+else
+  # Check if the error message contains the expected text
+  if grep -q "RMM requires LIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE to be defined" "${ERROR_FILE}"; then
+    echo "Test passed: Compilation failed with the expected error message"
+    echo "Error message:"
+    cat "${ERROR_FILE}"
```
Comment (bdice) [inline tests/libcudacxx_flag_test/libcudacxx_flag_test.sh:29]:
```suggestion
    # Don't show the error message, to avoid confusing it with a real error in the CI logs.
```

**Review by wence- — APPROVED** [review]
Trivial suggestions. Looks good, I think,

File: tests/libcudacxx_flag_test/libcudacxx_flag_test.sh [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+  # Check if the error message contains the expected text
+  if grep -q "RMM requires LIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE to be defined" "${ERROR_FILE}"; then
+    echo "Test passed: Compilation failed with the expected error message"
+    # Don't show the error message, to avoid confusing it with a real error in the CI logs.
+  else
+    echo "Test failed: Compilation failed but with an unexpected error message:"
+    cat "${ERROR_FILE}"
+    exit 1
+  fi
+fi
```
[the remark this answers is not in the document]
Comment (bdice) [reply tests/libcudacxx_flag_test/libcudacxx_flag_test.sh:34]: Yes, that is a good suggestion!

File: tests/libcudacxx_flag_test/libcudacxx_flag_test.sh [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+
+echo "Testing compilation failure when LIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE is not defined"
+echo "Using RMM include directory: ${RMM_INCLUDE_DIR}"
+
+# Create a temporary file for compilation errors
+ERROR_FILE=$(mktemp)
+trap 'rm -f "${ERROR_FILE}"' EXIT
+
+# Try to compile the file without defining LIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE
+if g++ -std=c++17 -I"${RMM_INCLUDE_DIR}" libcudacxx_flag_test.cpp -o libcudacxx_flag_test 2> "${ERROR_FILE}"; then
```
Comment (bdice) [inline tests/libcudacxx_flag_test/libcudacxx_flag_test.sh:21]:
```suggestion
g++ -std=c++17 -I"${RMM_INCLUDE_DIR}" libcudacxx_flag_test.cpp -o libcudacxx_flag_test 2> "${ERROR_FILE}"
if $?; then
```

File: tests/libcudacxx_flag_test/libcudacxx_flag_test.sh [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+
+echo "Testing compilation failure when LIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE is not defined"
+echo "Using RMM include directory: ${RMM_INCLUDE_DIR}"
+
+# Create a temporary file for compilation errors
+ERROR_FILE=$(mktemp)
+trap 'rm -f "${ERROR_FILE}"' EXIT
+
+# Try to compile the file without defining LIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE
+g++ -std=c++17 -I"${RMM_INCLUDE_DIR}" libcudacxx_flag_test.cpp -o libcudacxx_flag_test 2> "${ERROR_FILE}"
```
Comment (jameslamb) [inline tests/libcudacxx_flag_test/libcudacxx_flag_test.sh:21]:
```suggestion
set +e
g++ -std=c++17 -I"${RMM_INCLUDE_DIR}" libcudacxx_flag_test.cpp -o libcudacxx_flag_test 2> "${ERROR_FILE}"
set -e
```

I *think* this line is why this is currently failing in CI, like this:

```text
Testing compilation failure when LIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE is not defined
Using RMM include directory: /__w/rmm/rmm/tests/libcudacxx_flag_test/../../include
Error: Process completed with exit code 1.
```

([build link](https://github.com/rapidsai/rmm/actions/runs/13765081966/job/38489672536?pr=1852#step:9:6077))

You've set `set -e` at the top, which causes the script to exit with a non-0 exit code when any other command in the script does. This compile compile line is failing (as you expect!), but that `-e` is causing the script to exit before even entering this if-else block.

File: tests/libcudacxx_flag_test/libcudacxx_flag_test.sh [hunk 6]
```diff
@@ -0,0 +1,38 @@
...
+if $?; then
+  echo "Test failed: Compilation succeeded when it should have failed"
+  exit 1
+else
```
Comment (jameslamb) [inline tests/libcudacxx_flag_test/libcudacxx_flag_test.sh:25]: Very very minor style comment, but I'd remove the nesting here. Invoking `exit` is an early return, there's no need to `else` it.

Like this:

```bash
if $?; then
  echo "Test failed: Compilation succeeded when it should have failed"
  exit 1
fi

if grep -q "RMM requires LIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE to be defined" "${ERROR_FILE}"; then
    echo "Test failed: Compilation failed but with an unexpected error message:"
    cat "${ERROR_FILE}"
    exit 1
fi

echo "Test passed: Compilation failed with the expected error message"
exit 0
```

In my opinion, this makes it a little easier to read and to extend with more conditions. But do what you want with that suggestion, it's definitely not blocking and not an opinion I hold strongly.

**Review by jameslamb — APPROVED** [review]
Approving from the narrow `ci-codeowners` perspective (I did not review any of the C++ changes here). I left one suggestion for how to fix what I think is causing CI to fail here, and one other minor style suggestion.

**Review by harrism — APPROVED** [review]

**Comment by vyasr** [comment]
@bdice do you want to get this in? It looks like @jameslamb proposed a fix for the failures.

**Comment by bdice** [comment]
I will revisit this tomorrow. 25.04 would be nice but it’s not crucial and could go to 25.06.

File: tests/libcudacxx_flag_test/libcudacxx_flag_test.sh (hunk 6 above)
Comment (bdice) [reply tests/libcudacxx_flag_test/libcudacxx_flag_test.sh]: That's a great improvement. I applied this in 50ee60b9b1d8c5d16ec4cf3355d979dc3dad3d3b.
