### PR TITLE
Refactor device capability checks, fix prefetching bug on WSL

### LINKED ISSUE #2023: [BUG] Prefetching tests fail on WSL due to lack of concurrent managed access
**Describe the bug**

WSL systems use the Windows CUDA driver, which does not support concurrent managed access. This results in failures of RMM prefetching tests like so:

```
[ RUN      ] PrefetchTest/1.PointerAndSize
unknown file: Failure
C++ exception with description "CUDA error at: /home/coder/rmm/cpp/src/prefetch.cpp:40: cudaErrorInvalidDevice invalid device ordinal" thrown in the test body.
[  FAILED  ] PrefetchTest/1.PointerAndSize, where TypeParam = rmm::mr::managed_memory_resource (5 ms)
[ RUN      ] PrefetchTest/1.DeviceUVector
unknown file: Failure
C++ exception with description "CUDA error at: /home/coder/rmm/cpp/src/prefetch.cpp:40: cudaErrorInvalidDevice invalid device ordinal" thrown in the test body.
[  FAILED  ] PrefetchTest/1.DeviceUVector, where TypeParam = rmm::mr::managed_memory_resource (2 ms)
[ RUN      ] PrefetchTest/1.DeviceScalar
unknown file: Failure
C++ exception with description "CUDA error at: /home/coder/rmm/cpp/src/prefetch.cpp:40: cudaErrorInvalidDevice invalid device ordinal" thrown in the test body.
[  FAILED  ] PrefetchTest/1.DeviceScalar, where TypeParam = rmm::mr::managed_memory_resource (2 ms)
```

**Expected behavior**
Prefetching tests should be skipped on systems that do not support concurrent managed access.

A fix for this is ready in #2014.

### PR DESCRIPTION
**Pull request by bdice**
## Description
Refactors device capability checks, add concurrent managed access checks to skip prefetching tests on WSL (not supported).

One motivation for this refactoring is that the previous names really didn't make much sense. We created the `runtime_async_alloc::is_supported()` to check for CUDA 11.2+ support for runtime async allocation. However, we tacked on other features like `is_export_handle_type_supported(cudaMemAllocationHandleType)` and `is_hwdecompress_supported()` into the same struct. Those should have been their own features, not tied to `runtime_async_alloc`. Most of the changes in this PR are structurally similar to that.

Closes #2023.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rmm/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

File: cpp/src/prefetch.cpp [hunk 1]
```diff
@@ -14,26 +14,30 @@
  * limitations under the License.
  */
 
+#include <rmm/detail/runtime_capabilities.hpp>
 #include <rmm/prefetch.hpp>
 
 #include <cuda_runtime_api.h>
 
+#include <unordered_map>
```
Comment (Matt711) [inline cpp/src/prefetch.cpp]: Maybe?
```suggestion
```

Comment (bdice) [reply cpp/src/prefetch.cpp]: Good catch! Fixed in a1ff912.

**Review by vyasr — APPROVED** [review]
Approving build changes.
