### PR TITLE
Fix pool_memory_resource crash during process exit

### LINKED ISSUE #2366: Intermittent SIGSEGV at process exit when pool_memory_resource is held in the static per-device resource map
## Describe the bug

When a `rmm::mr::pool_memory_resource` is installed via `rmm::mr::set_current_device_resource(...)` and left in place until process exit, the program intermittently segfaults during `exit()`. The crash occurs inside `libcuda.so` under `cudaEventSynchronize`, called from `stream_ordered_memory_resource::release()` in the pool destructor.

## Steps to reproduce

Using a cuDF benchmark that installs a pool MR via `--rmm-mode pool` (the default for most NVBench benchmarks):

```bash
./cpp/build/latest/benchmarks/STRINGS_NVBENCH --profile --benchmark 0 --devices 0
```

Run a few times. Crash rate is ~60–80%; it is non-deterministic because it depends on teardown ordering between the CUDA primary context and the static containers that hold the pool.

RMM: `upstream/main` at `386f76d5` ("Merge pull request #2361 from rapidsai/staging").

## Expected behavior

The benchmark exits cleanly (exit code 0) after printing results.

## Actual behavior

Roughly 4/5 runs terminate with `SIGSEGV` after the last benchmark case has run and results have been printed. The crash is in process teardown, not in the benchmark itself.

### 1. Release-build segfault (original symptom)

`gdb` caught this on attempt 5 of a loop of STRINGS_NVBENCH runs:

```
Thread 1 "STRINGS_NVBENCH" received signal SIGSEGV, Segmentation fault.
#0  0x0000ffffe2a8c0d8 in ?? () from /lib/aarch64-linux-gnu/libcuda.so.1
#1  0x0000ffffe2a7a280 in cuEventSynchronize () from libcuda.so.1
#2  0x0000ffffeb2a7be4 in ?? () from libcudart.so.13
#3  0x0000ffffeb2e4464 in cudaEventSynchronize () from libcudart.so.13
#4  0x0000ffffeb454778 in rmm::mr::detail::pool_memory_resource_impl::~pool_memory_resource_impl() () from librmm.so
#5  0x0000aaaaaacabe6c in void cuda::__4::__dtor_fn<rmm::mr::pool_memory_resource>(void*, bool) ()
#6  0x0000ffffeb9f3f64 in std::map<int, cuda::mr::__4::__version_bump_ver4_::any_resource<cuda::mr::__4::device_accessible>, ...>::~map() () from libcudf.so
#7  0x0000ffffead4f228 in ?? () from libc.so.6
#8  0x0000ffffead4f30c in exit () from libc.so.6
#9  0x0000ffffead384c8 in ?? () from libc.so.6
#10 0x0000ffffead38598 in __libc_start_main () from libc.so.6
#11 0x0000aaaaaab09f78 in _start ()
```

### 2. Debug-build assertion reveals the underlying cuda error

Rebuilding only librmm as `CMAKE_BUILD_TYPE=Debug` (cudf stays Release) replaces the segfault with a clean `assert()` failure, which prints the exact cuda error that libcuda would have been about to mishandle:

```
CUDA Error detected. cudaErrorContextIsDestroyed context is destroyed
STRINGS_NVBENCH: cpp/include/rmm/mr/detail/stream_ordered_memory_resource.hpp:490:
  void rmm::mr::detail::stream_ordered_memory_resource<
        rmm::mr::detail::pool_memory_resource_impl,
        rmm::mr::detail::coalescing_free_list>::release():
  Assertion `status__ == cudaSuccess || status__ == cudaErrorCudartUnloading' failed.
```

With gdb:

```
#0  abort () from libc.so.6
#4  __assert_fail () from libc.so.6
#5  stream_ordered_memory_resource<...>::release at stream_ordered_memory_resource.hpp:490
#6  ~stream_ordered_memory_resource at stream_ordered_memory_resource.hpp:70
#7  ~pool_memory_resource_impl at pool_memory_resource_impl.cpp:45
#8  cuda::__4::__dtor_fn<rmm::mr::pool_memory_resource>
#9  std::map<int, any_resource<device_accessible>>::~map()    [libcudf.so]
#10 from libc.so.6
#11 exit () from libc.so.6
#12 __libc_start_main ()
```

So the cudart return value that libcuda was about to crash on is `cudaErrorContextIsDestroyed`. `RMM_ASSERT_CUDA_SUCCESS_SAFE_SHUTDOWN` currently only whitelists `cudaErrorCudartUnloading`, so in Debug builds the assert fires; in Release builds the whitelist is a no-op and cudart/libcuda proceed and SIGSEGV.

Other teardown states observed while experimenting: `cudaErrorDeviceUninitialized` ("invalid device context").

### 3. cudaEventSynchronize cannot be probe-safe

I tested whether checking `cudaEventSynchronize`'s return value (rather than just letting the assert handle it) is sufficient:

```cpp
auto const sync_status = cudaEventSynchronize(s_e.second.event);
if (sync_status == cudaErrorCudartUnloading ||
    sync_status == cudaErrorContextIsDestroyed ||
    sync_status == cudaErrorDeviceUninitialized) {
  cudaGetLastError();
  break;
}
```

This still segfaults in Release: cudart does not validate context state before forwarding to the driver. The synchronize call enters `cuEventSynchronize` and crashes in libcuda before returning anything. Backtrace (frame 4 at the modified source line):

```
#0  0x0000ffffe2a7c0d8 in ?? () from libcuda.so.1
#1  cuEventSynchronize () from libcuda.so.1
#2  from libcudart.so.13
#3  cudaEventSynchronize () from libcudart.so.13
#4  stream_ordered_memory_resource<...>::release (this=0x...) at stream_ordered_memory_resource.hpp:493
... same exit chain as above ...
```

### 4. cudaEventQuery also cannot be probe-safe

Since `cudaEventQuery` is documented as a non-blocking status probe, I tested whether cudart validates the context there before forwarding. It does not — `cudaEventQuery` segfaults the same way `cudaEventSynchronize` does:

```
#0  0x0000ffffe2a7bea8 in ?? () from libcuda.so.1
#1  cuEventQuery () from libcuda.so.1
#2  from libcudart.so.13
#3  cudaEventQuery () from libcudart.so.13
#4  stream_ordered_memory_resource<...>::release at stream_ordered_memory_resource.hpp:498
... same exit chain ...
```

So **no CUDA runtime API call is safe** once the primary context is destroyed during teardown. This matches the existing comment at `stream_ordered_memory_resource.hpp:307-311`:

> "Create a thread-local event for each device. These events are deliberately leaked since the destructor needs to call into the CUDA runtime and thread_local destructors (can) run below main: it is undefined behaviour to call into the CUDA runtime below main."

The thread-local-events path already handles this by never destroying; the destructor-time `release()` path does not, which is what this bug is about.

## Root cause

The static per-device resource map (`detail::get_ref_map()`'s `static std::map<..., any_resource<device_accessible>>`) holds the `pool_memory_resource` by value. Its dtor is registered with `__cxa_atexit` when the map is first used, and it runs during `__run_exit_handlers`. By that time the CUDA primary context has been destroyed (via cudart's own atexit hook and/or other DSOs' teardown), so the pool's `release()` calls `cudaEventSynchronize` on tracked events whose stream/context has been torn down. Cudart forwards into libcuda, which dereferences destroyed context state → `SIGSEGV` in Release, `cudaErrorContextIsDestroyed` → failed assert in Debug.

## Scope

Any `stream_ordered_memory_resource` subclass (e.g. `pool_memory_resource`) stored with static lifetime and not explicitly destroyed before `exit()` is affected. The same concern applies to `pool_memory_resource_impl::release()`'s upstream `deallocate_sync` calls when the upstream is `cuda_memory_resource`, since those also call into CUDA.

## Proposed fix

Detect teardown without calling into CUDA at all (using `std::atexit` + atomic flag, with LIFO registration ordered after the map's own dtor registration so the flag is set before the map's dtor runs). `release()` then short-circuits and leaks — the OS reclaims everything on process exit.

Expose this teardown detection as public API so memory-resource authors can adopt the same pattern in downstream MRs. Document the author contract: MR destructors must be safe to run during process exit, either by not calling CUDA APIs at all or by consulting the shutdown flag.

A PR implementing this will follow.

### PR DESCRIPTION
**Pull request by bdice**
## Description

Closes #2366.

Fixes the intermittent SIGSEGV at process exit when a stateful memory resource owned by RMM's internal per-device resource map is destroyed after the CUDA primary context has already been torn down.

### Root cause

`pool_memory_resource`'s destructor calls `stream_ordered_memory_resource::release()`, which calls `cudaEventSynchronize` / `cudaEventDestroy` on tracked events. When the pool is stored by value in the static `std::map` returned by `detail::get_ref_map()`, its destructor runs during process termination. At that point CUDA runtime/driver calls are unsafe: in Release builds cudart can forward into libcuda, where the driver dereferences destroyed context state and SIGSEGVs; in Debug builds cudart may return shutdown-related errors such as `cudaErrorContextIsDestroyed`.

The investigation in #2366 also showed that `cudaEventQuery` is not a safe probe here: it can crash the same way as `cudaEventSynchronize` once context state is gone.

### Fix

Add an internal process-exit hook for RMM's per-device resource map and a public query, `rmm::process_is_exiting()`, for RMM memory resource destructors installed in that map.

The C++ standard (post-C++11, [cppreference `std::exit`](https://en.cppreference.com/cpp/utility/program/exit.html)) guarantees:

> If the completion of the initialization of a static object A was sequenced-before the call to `std::atexit` for some function F, the call to F during termination is sequenced-before the start of the destruction of A.

`get_ref_map()` constructs the static map and then immediately calls `rmm::detail::register_process_exit_hook()`, which registers a single `std::atexit` callback. By the sequencing rule above, the callback runs before the map destructor and flips the flag observed by `rmm::process_is_exiting()`.

This intentionally does **not** support arbitrary user-created static or thread-local containers of RMM objects. The supported case is RMM's internal per-device resource map. The setter docstrings now explicitly say that any resource installed in the map whose destructor may call CUDA APIs must consult `rmm::process_is_exiting()` and skip those calls when it returns `true`.

### What changed

- `cpp/include/rmm/process_is_exiting.hpp`: new public query API and documentation for shutdown-sensitive destructors.
- `cpp/include/rmm/detail/runtime_shutdown.hpp` and `cpp/src/runtime_shutdown.cpp`: internal hook registration and flag implementation.
- `cpp/include/rmm/mr/per_device_resource.hpp`: registers the exit hook immediately after the static map is constructed, and documents the destructor requirements on the four `set_*_device_resource*` setters.
- `cpp/include/rmm/mr/detail/stream_ordered_memory_resource.hpp`: skips event cleanup during process exit.
- `cpp/src/mr/detail/pool_memory_resource_impl.cpp`: skips upstream block deallocation during process exit.
- `cpp/src/mr/detail/fixed_size_memory_resource_impl.cpp`: skips upstream block deallocation during process exit.
- `cpp/src/mr/detail/cuda_async_memory_resource_impl.cpp`: skips `cudaMemPoolDestroy` during process exit.
- `cpp/tests/process_is_exiting_tests.cpp`: basic public API tests.
- `cpp/tests/process_is_exiting_shutdown_test.cpp`: standalone process-lifecycle test proving that the flag is set before a checker registered before `get_ref_map()` runs at process termination.

### Verification

Reproducer from #2366: `./cpp/build/latest/benchmarks/STRINGS_NVBENCH --profile --benchmark 0 --devices 0` from rapidsai/cudf.

- Before: ~60–80% segfault rate at process exit.
- After (Release): 0 failures in 50 consecutive runs.
- After (Debug): 0 failures in 80 consecutive runs (30 + 50).

Local tests run during development:

- `PROCESS_IS_EXITING_TEST`
- `PROCESS_IS_EXITING_PTDS_TEST`
- `PROCESS_IS_EXITING_SHUTDOWN_TEST`
- relevant MR smoke tests including `POOL_MR_TEST`, `POOL_MR_PTDS_TEST`, `FIXED_SIZE_MR_REF_TEST`, `CUDA_ASYNC_MR_SHARED_CUDART_TEST`, `CUDA_ASYNC_MR_STATIC_CUDART_TEST`, and `ERROR_MACROS_TEST`

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rmm/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

File: cpp/src/runtime_shutdown.cpp [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+{
+  // atexit/__cxa_atexit run callbacks in LIFO order. Callers must invoke this after the static
+  // object whose destructor needs to see the flag has been constructed, so this callback is
+  // appended to the queue after that object's destructor has been registered; the callback will
+  // then run before that destructor.
+  static std::atomic<bool> registered{false};
+  bool expected = false;
+  if (registered.compare_exchange_strong(expected, true, std::memory_order_acq_rel)) {
+    std::atexit([]() noexcept { exiting_flag().store(true, std::memory_order_release); });
+  }
```
[the remark this answers is not in the document]
Comment (bdice) [reply cpp/src/runtime_shutdown.cpp]: What can cause this to fail?

File: docs/cpp/memory_resources/memory_resources.md [hunk 2]
```diff
@@ -1,5 +1,50 @@
 # Memory Resources
 
+## Authoring custom memory resources
```
Comment (bdice) [inline docs/cpp/memory_resources/memory_resources.md]: We will want to move this to the user guide (#2087).

File: cpp/src/runtime_shutdown.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (bdice) [reply cpp/src/runtime_shutdown.cpp]: Thanks! I'm going to call this resolved.

File: cpp/include/rmm/mr/per_device_resource.hpp [hunk 3]
```diff
@@ -176,6 +188,13 @@ inline cuda::mr::any_resource<cuda::mr::device_accessible> set_per_device_resour
  * `device_async_resource_ref` is undefined if used while the active CUDA device is a different
  * device from the one that was active when the memory resource was created.
  *
+ * @note The underlying resource referenced by `new_resource_ref` must be safe to destroy at
+ * process shutdown. The per-device resource map keeps a reference alive until process exit, so
+ * the underlying resource's destructor may run after the CUDA primary context has been
+ * destroyed -- at that point calling into the CUDA runtime is undefined behavior. Resource
+ * destructors must either not call CUDA APIs at all, or consult `rmm::process_is_exiting()` and
+ * skip CUDA calls when it returns `true`.
```
[the remark this answers is not in the document]
Comment (bdice) [reply cpp/include/rmm/mr/per_device_resource.hpp]: The ref-based setters are deprecated, but they do create owning copies of the underlying resource for storage in the map. This is reasonable to keep as-is until those functions are removed.

File: cpp/include/rmm/mr/detail/stream_ordered_memory_resource.hpp
Comment (wence-) [inline cpp/include/rmm/mr/detail/stream_ordered_memory_resource.hpp:499]: clearing the free blocks calls into the runtime (because it will call cudafree and friends).

This should be:

```
void release()
{
   if (rmm::process_is_exiting()) {
       return;
   }
   ...
}
```

File: cpp/src/runtime_shutdown.cpp [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+  // The C++ standard guarantees that if a static object's construction is sequenced-before a
+  // call to std::atexit, the atexit callback runs before that object's destructor at
+  // termination (see https://en.cppreference.com/cpp/utility/program/exit). Callers must
+  // therefore invoke this function after constructing the static object whose destructor needs
+  // to observe the exit flag.
+  static std::atomic<bool> registered{false};
+  bool expected = false;
+  if (registered.compare_exchange_strong(expected, true, std::memory_order_acq_rel)) {
+    std::atexit([]() noexcept { exiting_flag().store(true, std::memory_order_release); });
+  }
```
Comment (wence-) [inline cpp/src/runtime_shutdown.cpp]: Use `std::call_once`

File: cpp/include/rmm/detail/runtime_shutdown.hpp [hunk 5]
```diff
@@ -0,0 +1,24 @@
...
+/**
+ * @brief Register the atexit callback that flips the flag observed by `rmm::process_is_exiting()`.
+ *
+ * Idempotent: safe to call from multiple places; only the first call registers the callback.
+ * Callers must invoke this after constructing any static object whose destructor may run during
+ * process exit and needs to consult `rmm::process_is_exiting()`. The C++ standard guarantees
+ * that if a static object's construction is sequenced-before a `std::atexit` call, the atexit
+ * callback runs before that object's destructor at termination.
+ */
+RMM_EXPORT void register_process_exit_hook() noexcept;
```
Comment (wence-) [inline cpp/include/rmm/detail/runtime_shutdown.hpp:19]: Why is this in a detail header, yet exported?

In fact, why does this header exist at all, let's just shovel it all into `process_is_exiting.hpp`.

File: cpp/src/runtime_shutdown.cpp [hunk 6]
```diff
@@ -0,0 +1,43 @@
...
+#include <rmm/detail/runtime_shutdown.hpp>
+#include <rmm/process_is_exiting.hpp>
+
+#include <atomic>
+#include <cstdlib>
+
+namespace RMM_NAMESPACE {
+
+namespace {
+
```
Comment (wence-) [inline cpp/src/runtime_shutdown.cpp:17]: I think this whole implementation can be simple.

```
namespace {
std::once_flag registered;
std::atomic<bool> exiting{false}
}
namespace detail {
void register_atexit_hook() {
    std::call_once(registered, [&exiting]() { 
        auto err = std::atexit([&exiting]() noexcept { exiting.store(true, std::memory_order_release); });
        RMM_EXPECTS_FATAL(err == 0, "Unable to register atexit handler");
    });
}
}
bool process_is_exiting() noexcept {
  return exiting.load(std::memory_order_acquire);
}


```

File: cpp/include/rmm/mr/per_device_resource.hpp [hunk 7]
```diff
@@ -76,6 +77,11 @@ RMM_EXPORT inline auto& get_ref_map()
 {
   static std::map<cuda_device_id::value_type, cuda::mr::any_resource<cuda::mr::device_accessible>>
     device_id_to_resource;
+  // The map's destructor may run owning resources' destructors during process exit, when calling
+  // into the CUDA runtime is undefined behavior. Register the process-exit hook here, right after
+  // the map is constructed: the C++ standard guarantees that an atexit callback registered after
+  // a static object's construction runs before that object's destructor at termination.
+  rmm::detail::register_process_exit_hook();
```
Comment (wence-) [inline cpp/include/rmm/mr/per_device_resource.hpp]: If we didn't want to use an atexit hook we could instead have an object that modifies a static variable. That might be simpler?

```
namespace {
    struct ShutdownFlag {
        ~ShutdownFlag() { flag.store(true, std::memory_order_release); }
        static std::atomic<bool> flag;
    }
    bool ShutdownFlag::flag = false;
}
namespace detail {
    bool is_shutting_down { return ShutdownFlag::flag.load(std::memory_order_acquire); }
}
// and now here;
{
static std::map<...> device_id_to_resource;
static shutdownobj = ShutdownFlag{};
```

`~ShutdownFlag()` will run before `~device_id_to_resource()` as required.

File: cpp/include/rmm/process_is_exiting.hpp [hunk 8]
```diff
@@ -0,0 +1,56 @@
...
+ * @addtogroup memory_resources
+ * @{
+ * @file
+ */
+
+/**
+ * @brief Returns `true` if the process has entered `exit()` / atexit handler execution.
+ *
+ * Destructors of static objects, as well as atexit handlers registered by other DSOs, can run
+ * after `main()` has returned. At that point calling into the CUDA runtime or driver is
```
Comment (wence-) [inline cpp/include/rmm/process_is_exiting.hpp]:
```suggestion
 * Destructors of static objects, as well as atexit handlers registered by other DSOs, will
 * after `main()` has returned. At that point calling into the CUDA runtime or driver is
```

File: cpp/src/mr/detail/cuda_async_memory_resource_impl.cpp [hunk 9]
```diff
@@ -66,7 +67,12 @@ cuda_async_memory_resource_impl::cuda_async_memory_resource_impl(
 
 cuda_async_memory_resource_impl::~cuda_async_memory_resource_impl()
 {
-  RMM_ASSERT_CUDA_SUCCESS_SAFE_SHUTDOWN(cudaMemPoolDestroy(pool_handle()));
+  // During process exit, calling into CUDA is undefined behavior once the primary context has
+  // been destroyed. Leak the memory pool in that case; the OS reclaims it when the process
+  // exits. See rmm/process_is_exiting.hpp.
```
Comment (wence-) [inline cpp/src/mr/detail/cuda_async_memory_resource_impl.cpp]: Let us not replicate this comment everywhere, it is described in detail via the process_is_exiting docs.

Also, prefer this pattern for dtors I think:

```
foo_impl::~foo_impl()
{
   if (rmm::process_is_exiting()) {
       return;
   }
   cleanup()
}
```

File: cpp/src/mr/detail/fixed_size_memory_resource_impl.cpp [hunk 10]
```diff
@@ -93,9 +94,14 @@ void fixed_size_memory_resource_impl::release()
...
-    upstream_mr_.deallocate_sync(
-      block.pointer(), upstream_chunk_size_, rmm::CUDA_ALLOCATION_ALIGNMENT);
+  // During process exit, calling into CUDA (even via the upstream resource) is undefined
+  // behavior once the primary context has been destroyed. Leak upstream blocks in that case;
+  // the OS reclaims them when the process exits. See rmm/process_is_exiting.hpp.
+  if (!rmm::process_is_exiting()) {
+    for (auto block : upstream_blocks_) {
+      upstream_mr_.deallocate_sync(
+        block.pointer(), upstream_chunk_size_, rmm::CUDA_ALLOCATION_ALIGNMENT);
+    }
```
Comment (wence-) [inline cpp/src/mr/detail/fixed_size_memory_resource_impl.cpp]:
```suggestion
  if (rmm::process_is_exiting()) { return; }
  for (auto block : upstream_blocks_) {
    upstream_mr_.deallocate_sync(
      block.pointer(), upstream_chunk_size_, rmm::CUDA_ALLOCATION_ALIGNMENT);
  }
```

File: cpp/src/mr/detail/pool_memory_resource_impl.cpp [hunk 11]
```diff
@@ -170,9 +171,14 @@ void pool_memory_resource_impl::release()
...
-    get_upstream_resource().deallocate_sync(
-      block.pointer(), block.size(), rmm::CUDA_ALLOCATION_ALIGNMENT);
+  // During process exit, calling into CUDA (even via the upstream resource) is undefined
+  // behavior once the primary context has been destroyed. Leak upstream blocks in that case;
+  // the OS reclaims them when the process exits. See rmm/process_is_exiting.hpp.
+  if (!rmm::process_is_exiting()) {
+    for (auto block : upstream_blocks_) {
+      get_upstream_resource().deallocate_sync(
+        block.pointer(), block.size(), rmm::CUDA_ALLOCATION_ALIGNMENT);
+    }
```
Comment (wence-) [inline cpp/src/mr/detail/pool_memory_resource_impl.cpp]: et seq., throughout

**Review by wence- — CHANGES_REQUESTED** [review]

File: cpp/include/rmm/mr/per_device_resource.hpp (hunk 7 above)
Comment (wence-) [reply cpp/include/rmm/mr/per_device_resource.hpp]: I guess that approach doesn't allow you to detect shutdown in `cuda_stream` dtors. However, arguably I think that is not necessary. `cuda_stream`s are never kept alive by static lifetime objects in RMM. If we migrate to CCCL `cuda::stream` they're not going to do this dance we're doing here

File: cpp/include/rmm/detail/runtime_shutdown.hpp [hunk 12]
```diff
@@ -0,0 +1,24 @@
...
+
+#include <rmm/detail/export.hpp>
+
+namespace RMM_NAMESPACE {
+namespace detail {
+
+/**
+ * @brief Register the atexit callback that flips the flag observed by `rmm::process_is_exiting()`.
+ *
+ * Idempotent: safe to call from multiple places; only the first call registers the callback.
```
Comment (vyasr) [inline cpp/include/rmm/detail/runtime_shutdown.hpp]: This statement is not true. I am trying to decide how much we should care about actually fixing the problem there.

A single atexit hook is not sufficient here. Consider the following code:

```cpp
struct X {
  ~X() { cudaFree(0); }
};

void f() {
  static X x;
  register_process_exit_hook();
}

void g() {
  static X y;
  register_process_exit_hook();
}

int main() {
  f();
  g();
}
```

When `g` runs the atexit handler has already been created, so it will not reregister. That means that the atexit handler will be sequenced before the destruction of `y`, so the destruction of `y` is unsafe.

@wence- asked about the current mixed public/private state of the function below. If we actually intend to support the above case, we need this to be a publicly exposed function in a header, and rather than storing a single value it needs to store one lock per handler. For example you could push a new atomic into a vector each time and return that index so that `process_is_exiting` could instead be `atexit_handler_has_run(int index)`.  That raises another more subtle problem, which is that the standard limits the number of atexit handlers to 32.

We need to decide the scope of this functionality. If it's only use case is for rmm's own per-device map, then we should hide the function. OTOH if we anticipate users storing memory resources in other objects with static scope Then we need to make sure that they have access as well. In that case, we have to worry about the total number of atexit handlers that are registered, although I don't think we have to support over 32.

**Review by vyasr — CHANGES_REQUESTED** [review]

File: cpp/include/rmm/detail/runtime_shutdown.hpp (hunk 12 above)
Comment (wence-) [reply cpp/include/rmm/detail/runtime_shutdown.hpp]: > We need to decide the scope of this functionality. If it's only use case is for rmm's own per-device map, then we should hide the function. OTOH if we anticipate users storing memory resources in other objects with static scope Then we need to make sure that they have access as well. In that case, we have to worry about the total number of atexit handlers that are registered, although I don't think we have to support over 32.

My take: we document it is UB to store RMM objects with static (or thread-local) scope.

We do all this dance privately just for the per-device map until we can kill it with fire.

File: cpp/include/rmm/detail/runtime_shutdown.hpp (hunk 5 above)
Comment (bdice) [reply cpp/include/rmm/detail/runtime_shutdown.hpp:19]: I tried to combine it in `process_is_exiting.hpp` but that didn't work out.

`register_process_exit_hook()` is not public API. When I briefly moved the declaration into the public header, Doxygen immediately started treating it as part of the exposed surface unless I added suppression markup around it. Doxygen ignores `detail/` headers. The separate `detail` header avoids that.

It still needs external linkage because it is defined in the library and called from inline code in `per_device_resource.hpp`, so the declaration has to be visible to includers and the symbol has to be linkable, but the intent is still “internal mechanism, not supported API.”

File: cpp/include/rmm/mr/detail/stream_ordered_memory_resource.hpp
Comment (bdice) [reply cpp/include/rmm/mr/detail/stream_ordered_memory_resource.hpp:499]: Fixed in 561ce688.

File: cpp/src/runtime_shutdown.cpp (hunk 4 above)
Comment (bdice) [reply cpp/src/runtime_shutdown.cpp]: Fixed in 573dd782.

File: cpp/src/mr/detail/cuda_async_memory_resource_impl.cpp (hunk 9 above)
Comment (bdice) [reply cpp/src/mr/detail/cuda_async_memory_resource_impl.cpp]: Fixed in 561ce688.

File: cpp/src/mr/detail/fixed_size_memory_resource_impl.cpp (hunk 10 above)
Comment (bdice) [reply cpp/src/mr/detail/fixed_size_memory_resource_impl.cpp]: Fixed in 561ce688.

File: cpp/src/mr/detail/pool_memory_resource_impl.cpp (hunk 11 above)
Comment (bdice) [reply cpp/src/mr/detail/pool_memory_resource_impl.cpp]: Fixed in 561ce688.

File: cpp/include/rmm/mr/per_device_resource.hpp (hunk 7 above)
Comment (bdice) [reply cpp/include/rmm/mr/per_device_resource.hpp]: Streams were fixed in 561ce688.

File: cpp/include/rmm/process_is_exiting.hpp (hunk 8 above)
Comment (bdice) [reply cpp/include/rmm/process_is_exiting.hpp]: Fixed in 4a814f36.

File: cpp/include/rmm/detail/runtime_shutdown.hpp (hunk 12 above)
Comment (bdice) [reply cpp/include/rmm/detail/runtime_shutdown.hpp]: I noted the UB in 4a814f36.

Comment (bdice) [reply cpp/include/rmm/detail/runtime_shutdown.hpp]: > That raises another more subtle problem, which is that the standard limits the number of atexit handlers to 32.

Emphasis added:
> The implementation is guaranteed to support the registration of **at least 32 functions. The exact limit is implementation-defined.**

https://en.cppreference.com/cpp/utility/program/atexit

To verify,

```cpp
long limit = sysconf(_SC_ATEXIT_MAX);
```

gives me 2147483647. I don't expect this cap to affect us.

File: cpp/src/runtime_shutdown.cpp (hunk 6 above)
Comment (bdice) [reply cpp/src/runtime_shutdown.cpp:17]: Updated in 520d6f9f to store the `std::atexit` return value in `registration_status` before checking it with `RMM_EXPECTS`.

**Review by wence- — APPROVED** [review]
I thought we wouldn't want process_is_exiting in the public API but I realise we need it so that downstream authors of mrs can DTRT.

File: cpp/include/rmm/detail/runtime_shutdown.hpp (hunk 12 above)
Comment (vyasr) [reply cpp/include/rmm/detail/runtime_shutdown.hpp]: Yes, I realize that most implementations set a much higher value. I wouldn't want to rely on that in the case where we we're providing a new atexit handler for every other object. In any case, as long as we're scoping this for internal use only with the per-device map I'm fine leaving it as-is.

File: cpp/tests/process_is_exiting_shutdown_test.cpp [hunk 13]
```diff
@@ -0,0 +1,54 @@
...
+ */
+
+#include <rmm/mr/per_device_resource.hpp>
+#include <rmm/process_is_exiting.hpp>
+
+#include <cstdlib>
+
+/*
+ * Standalone test that verifies rmm::process_is_exiting() reports true while the C runtime is
+ * executing atexit handlers. The fix in rapidsai/rmm#2367 depends on this behavior: resource
```
Comment (vyasr) [inline cpp/tests/process_is_exiting_shutdown_test.cpp]: Nit: I'd remove the ref to the specific issue/PR, I assume AI added it.

File: cpp/tests/process_is_exiting_shutdown_test.cpp [hunk 14]
```diff
@@ -0,0 +1,54 @@
...
+ * destructors running during exit() must observe the flag as set so that they can skip CUDA
+ * calls.
+ *
+ * The C++ standard guarantees that if the completion of the initialization of a static object A
+ * is sequenced-before a call to std::atexit(F), then F runs before A's destructor at
+ * termination. RMM exploits this by having register_process_exit_hook() register a flag-setter
+ * via std::atexit on first use; it is called from get_ref_map() immediately after the static
+ * map is constructed, so the flag is observed as true during that map's destructor.
```
Comment (vyasr) [inline cpp/tests/process_is_exiting_shutdown_test.cpp]: All of this is (or should be) explained in the source, not the test.
```suggestion
```

File: cpp/tests/process_is_exiting_shutdown_test.cpp [hunk 15]
```diff
@@ -0,0 +1,54 @@
...
+ *      calls _Exit(1) to signal failure.
+ *
+ * CTest checks the exit status.
+ */
+
+namespace {
+
+void checker() noexcept
+{
+  if (!rmm::process_is_exiting()) { std::_Exit(1); }
```
Comment (vyasr) [inline cpp/tests/process_is_exiting_shutdown_test.cpp]: Probably worth a note that you're intentionally using `std::_Exit` rather than `std::exit` since we're mid-termination and since this is a test we also don't need proper cleanup to occur afterwards.

**Review by vyasr — APPROVED** [review]
Some improvements can be made to the comments but the implementation looks fine now.
