### PR TITLE
Fix allocate_sync usage with non-blocking streams

### LINKED ISSUE #2156: [BUG] cuda_async_memory_resource.allocate_sync doesn't
**Describe the bug**

`allocate_sync` promises that the pointer is immediately valid on all streams, but, consider the following:

```c++
#include <rmm/cuda_stream.hpp>
#include <rmm/mr/cuda_async_memory_resource.hpp>
int main() {

  auto mr = rmm::mr::cuda_async_memory_resource{};
  auto stream = rmm::cuda_stream(rmm::cuda_stream::flags::non_blocking);

  void *ptr = mr.allocate_sync(256);
  mr.deallocate(stream, ptr, 256);
  return 0;
}
```

```
$ compile...
$ compute-sanitizer --track-stream-ordered-races=all ./bug
========= COMPUTE-SANITIZER
========= Free-before-alloc on allocation of size 256 bytes at 0x3366000000
=========     Address 0x3366000000 is potentially free'd before it is allocated
=========     
=========     Saved host backtrace up to driver entry point at cudaFreeAsync time
=========         Host Frame: cuMemFreeAsync [0x3a2a5f] in libcuda.so.1
=========         Host Frame:  [0x15c2f] in libcudart.so.13
=========         Host Frame: cudaFreeAsync [0x779ff] in libcudart.so.13
=========         Host Frame: rmm::mr::cuda_async_memory_resource::do_deallocate(void*, unsigned long, rmm::cuda_stream_view) in cuda_async_memory_resource.hpp:186 [0x35a7] in bug
=========         Host Frame: main in io-bug.cxx:9 [0x3110] in bug
=========     
=========     Saved host backtrace up to driver entry point at cudaMallocAsync time
=========         Host Frame: cuMemAllocFromPoolAsync [0x3a2bdf] in libcuda.so.1
=========         Host Frame:  [0x15a5e] in libcudart.so.13
=========         Host Frame: cudaMallocFromPoolAsync [0x77c2e] in libcudart.so.13
=========         Host Frame: rmm::mr::cuda_async_view_memory_resource::do_allocate(unsigned long, rmm::cuda_stream_view) in cuda_async_view_memory_resource.hpp:87 [0x4a05] in bug
=========         Host Frame: main in nvtxInitDefs.h:480 [0x30f1] in bug
========= 
========= ERROR SUMMARY: 1 error
```

The problem here is that the implementation of `allocate_sync` in `device_memory_resource` calls into the concrete implementation's `do_allocate` with:

```
do_allocate(bytes, cuda_stream_view{});
```

where that nullary ctor is a view of the default stream.

But, this assumes that the default stream synchronises with all streams.

This is not true if you created your stream with `cudaStreamNonBlocking`.

Contrast, if I switch the stream creation flags to `sync_default` then compute-sanitizer (correctly) doesn't complain.

To fix this, we need to sync the stream we use inside `allocate_sync` after doing the actual allocation.

CCCL uses an internal "side" stream for this purpose. The matching `deallocate_sync` comes with the requirement that the user must have synchronised all work before calling `deallocate_sync` (and must have allocated with `allocate_sync`).

### PR DESCRIPTION
**Pull request by bdice**
## Description

`allocate_sync` promises that the returned pointer is immediately valid on all streams. However, the previous implementation only allocated on the default stream without synchronizing it. This caused race conditions when using non-blocking streams, as the allocation might not be visible to other streams.

This fix adds a synchronization of the default stream after allocation to ensure the pointer is immediately valid on all streams, including non-blocking streams.

Closes #2156.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rmm/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

File: cpp/include/rmm/mr/device_memory_resource.hpp [hunk 1]
```diff
@@ -98,6 +98,8 @@ class device_memory_resource {
    * The returned pointer will have 256 byte alignment regardless of the value
    * of alignment. Higher alignments must use the aligned_resource_adaptor.
    *
+   * The returned pointer is immediately valid on all streams.
+   *
    * @throws rmm::bad_alloc When the requested `bytes` cannot be allocated.
```
Comment (wence-) [inline cpp/include/rmm/mr/device_memory_resource.hpp:103]: Maybe add a note to `deallocate_sync` that "All stream-ordered work on `ptr` must be complete before calling this function otherwise behavior is undefined"?

Comment (bdice) [reply cpp/include/rmm/mr/device_memory_resource.hpp:103]: Done in 8667b27.
