### PR TITLE
Fix pool_memory_resource failure when init and max pool sizes are equal

### LINKED ISSUE #527: [BUG] pool maximum_pool_size cannot equal initial_pool_size
I ran into this while trying to cap the pool from growing. If I ask the pool_memory_resource to initialize with the same number for `initial_pool_size` and `maximum_pool_size`, I get `Initial pool size exceeds the maximum pool size!`. 

This looks to be because we `align_up` the `initial_pool_size` but this doesn't happen to `maximum_pool_size`. I can think of some ways of fixing it but not sure what is the correct way:

- One way is to require the user to call into this constructor with sizes corresponding to the aligned versions of init and max, 
- Another way is for the constructor to re-set `maximum_pool_size` to `initial_pool_size` (after alignment) if the user-provided settings match, and `abs(maxium_pool_size - initial_pool_size) <= alignment`.

### PR DESCRIPTION
**Pull request by harrism**
Fixes #527 

Adds a simple alignment call on the max pool size to ensure setting the initial size and the maximum size the same will not cause a failure. Previously some values would fail because init was aligned up and max was not, so it would end up smaller than the initial pool size.

Also adds a test.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by jrhemstad** [comment]
So I thought about this when I refactored it, and my thinking was that we should respect the exact value of `max_pool_size`. I think of `initial_pool_size` as the _minimum_ size of the initial pool, whereas the `maximum_pool_size` should be respected as the exact max. Furthermore, if someone were to set a max to the exact amount of bytes left on the GPU and it wasn't a multiple of `256` bytes, then we'd be setting a max higher than what is actually available. 

That said, you should be able to set an initial and maximum pool size that are the same value. I just don't know yet the right way to support that. We could require the initial and max pool sizes to already be a multiple of `256` so we don't have to worry about aligning it ourselves.

**Comment by harrism** [comment]
I could change from this: 

```
maximum_pool_size_ = rmm::detail::align_up(
       (maximum_pool_size == default_maximum_size) ? free : maximum_pool_size, allocation_alignment);

     RMM_EXPECTS(pool_size() <= maximum_pool_size_,
                 "Initial pool size exceeds the maximum pool size!");
```

To this:

```
maximum_pool_size_ = (maximum_pool_size == default_maximum_size) ? free : maximum_pool_size;

     RMM_EXPECTS(pool_size() <= rmm::detail::align_up(maximum_pool_size_, allocation_alignment),
                 "Initial pool size exceeds the maximum pool size!");
```

This would allow the case where they are equal but unaligned to pass, and would also respect the exact maximum size specified if and when the pool attempts to grow.

**Comment by harrism** [comment]
@jrhemstad I did what you suggest, have a look.

File: include/rmm/mr/device/pool_memory_resource.hpp [hunk 1]
```diff
@@ -89,12 +90,25 @@ class pool_memory_resource final
...
-    current_pool_size_ = rmm::detail::align_up(initial_pool_size, allocation_alignment);
-    maximum_pool_size_ = (maximum_pool_size == default_maximum_size) ? free : maximum_pool_size;
+
+    initial_pool_size = (initial_pool_size == default_initial_size)
+                          ? rmm::detail::align_up(std::min(free, total / 2), allocation_alignment)
+                          : initial_pool_size;
+    current_pool_size_ = initial_pool_size;
+    maximum_pool_size_ = (maximum_pool_size == default_maximum_size)
+                           ? rmm::detail::align_up(free, allocation_alignment)
+                           : maximum_pool_size;
```
Comment (jrhemstad) [inline include/rmm/mr/device/pool_memory_resource.hpp:111]: I think this is a bug. This will end up setting the `maximum_pool_size` larger than `free` if `free` is not a multiple of 256. This should probably round _down_ to the next multiple of 256.

Comment (harrism) [reply include/rmm/mr/device/pool_memory_resource.hpp:111]: Argh, you are right. We need a n align down function.

Comment (harrism) [reply include/rmm/mr/device/pool_memory_resource.hpp]: Fixed.

File: include/rmm/mr/device/pool_memory_resource.hpp [hunk 2]
```diff
@@ -89,12 +90,25 @@ class pool_memory_resource final
         return upstream_mr;
       }()}
   {
+    RMM_EXPECTS(
```
Comment (jrhemstad) [inline include/rmm/mr/device/pool_memory_resource.hpp:93]: Docs should be updated to reflect that these args need to be a multiple of `pool_memory_resource::allocation_alignment`.

Comment (harrism) [reply include/rmm/mr/device/pool_memory_resource.hpp:97]: Added @throws docs.

**Review by jrhemstad — APPROVED** [review]

File: CHANGELOG.md [hunk 3]
```diff
@@ -12,6 +12,8 @@
 
 ## Bug Fixes
 
+- PR #534 Fix pool_memory_resource failure when init and max pool sizes are equal
```
Comment (codereport) [inline CHANGELOG.md:15]:
```suggestion
- PR #534 Fix `pool_memory_resource` failure when init and max pool sizes are equal
```

**Review by codereport — APPROVED** [review]
LGTM
