### PR TITLE
[REVIEW] Enforce default visibility for `get_map`.

### LINKED ISSUE #826: [BUG] Global static variable in inlined function.
**Describe the bug**

Hi, I'm trying to get rmm to work in XGBoost across Python and C++ code base.  One issue I found is the global variable `device_id_to_resource` returned by `rmm::mr::detail::get_map`.  The `get_map` function is inlined, so when XGBoost is compiled with:

``` cmake
    set_target_properties(${target} PROPERTIES
      C_VISIBILITY_PRESET hidden
      CXX_VISIBILITY_PRESET hidden
      CUDA_VISIBILITY_PRESET hidden
    )
```
different static variables are returned when called in C++ and called in Python.  I tried to print out the address of returned map in `set_per_device_resource` (called in Python `reinitialize`) and `get_per_device_resource`(called during construction of `device_uvector`),  and can confirm the returned maps have different addresses.  This leads to user configuration not being honored in XGBoost c++ code base.  Actually if I use gdb to break the function, the one called in Python is completely ignored.

### PR DESCRIPTION
**Pull request by trivialfis**
Define macros used for specifying symbol visibility and use it on `get_map`.  The macros are only useful for gcc/clang with glibc on Linux.  Sorry I'm not familiar with other platforms.

Close https://github.com/rapidsai/rmm/issues/826 .

> 1. Please ensure that you have written units tests for the changes made and/or features added.

I'm not sure how to test this on CI.

### CODE REVIEW

**Comment by trivialfis** [comment]
Please help with the label, I don't have permission to edit the label on GitHub.

**Comment by harrism** [comment]
@trivialfis we are one day from code freeze for 21.08 so please retarget to 21.10.  Thanks!

**Comment by trivialfis** [comment]
Got it, will reopen the PR.

File: include/rmm/mr/device/per_device_resource.hpp [hunk 1]
```diff
@@ -95,7 +96,8 @@ inline std::mutex& map_lock()
   return map_lock;
 }
 
-inline auto& get_map()
+// Must have default visibility, see: https://github.com/rapidsai/rmm/issues/826
+RMM_EXPORT inline auto& get_map()
```
Comment (harrism) [inline include/rmm/mr/device/per_device_resource.hpp:100]: Don't you need this on all functions in this file?

Comment (trivialfis) [reply include/rmm/mr/device/per_device_resource.hpp:100]: I tested it with XGBoost and it works fine.  I'm not entirely sure what's happening exactly during runtime linking.  I guess as long as this function is not inlined and the linker can find the right symbol it should be fine?

**Comment by trivialfis** [comment]
I moved the PR to https://github.com/rapidsai/rmm/pull/834 as requested.

**Comment by harrism** [comment]
You don't need a new PR. You could have just clicked "edit" next to the title and selected 21.10. Then merge 21.10 into your branch.

**Comment by trivialfis** [comment]
Let me try that.

**Comment by trivialfis** [comment]
> You don't need a new PR. You could have just clicked "edit" next to the title and selected 21.10. Then merge 21.10 into your branch.

Good to learn something new every day. ;-)

**Comment by jrhemstad** [comment]
rerun tests

**Review by rongou — APPROVED** [review]

**Comment by trivialfis** [comment]
rerun tests

**Review by jrhemstad — APPROVED** [review]

**Comment by jrhemstad** [comment]
@gpucibot merge
